import { LegalDocument } from "../types";

export const acceptableUse: LegalDocument = {
  slug: "acceptable-use",
  title: "Acceptable Use Policy",
  lastUpdated: "March 18, 2026",
  version: "1.0",
  summary: "Comprehensive guidelines for using the Vayva platform responsibly, safely, and in compliance with applicable laws.",
  sections: [
    {
      heading: "1. General Principles",
      content: [
        "Vayva is dedicated to providing a safe, reliable, and trustworthy platform for commerce. This policy sets out the rules for participating in the Vayva community.",
        "By using Vayva, you agree to conduct your business with integrity, treat all users with respect, and comply with all applicable laws and regulations.",
      ],
      type: "text",
    },
    {
      heading: "2. Prohibited Activities - Illegal & Fraudulent Conduct",
      content: [
        "You must NOT use Vayva for:",
        "• **Illegal Activities**: Any activity that violates applicable local, state, national, or international laws",
        "• **Fraud**: Deceptive practices, false advertising, pyramid schemes, Ponzi schemes, or financial scams",
        "• **Money Laundering**: Attempting to disguise the origins of illegally obtained money",
        "• **Terrorism Financing**: Providing funds for terrorist organizations or activities",
        "• **Sanctions Violations**: Doing business with individuals, organizations, or countries subject to trade sanctions",
        "• **Identity Theft**: Impersonating another person, business, or entity without authorization",
        "• **Phishing**: Attempting to acquire sensitive information by masquerading as a trustworthy entity",
      ],
      type: "definitions",
    },
    {
      heading: "3. Prohibited Activities - Harmful Content & Communications",
      content: [
        "You must NOT:",
        "• **Spam**: Send unsolicited bulk messages, advertisements, or promotional content through Vayva's messaging systems",
        "• **Harassment & Bullying**: Threaten, intimidate, or harass other users, customers, or Vayva staff",
        "• **Hate Speech**: Promote violence, hatred, or discrimination based on race, ethnicity, religion, gender, sexual orientation, disability, or other protected characteristics",
        "• **Malicious Code**: Distribute viruses, malware, ransomware, trojans, worms, or any harmful code designed to damage or gain unauthorized access to computer systems",
        "• **False Information**: Deliberately spread misinformation that could cause harm (e.g., false health claims, dangerous product claims)",
      ],
      type: "text",
    },
    {
      heading: "4. Prohibited Activities - Platform Security & Integrity",
      content: [
        "You must NOT:",
        "• **DDoS Attacks**: Launch distributed denial-of-service attacks or attempt to overwhelm Vayva's servers",
        "• **Unauthorized Access**: Gain or attempt to gain unauthorized access to Vayva's systems, networks, or data through hacking, password mining, or other means",
        "• **Interference**: Disrupt, degrade, or impair the performance of Vayva's services or prevent others from using them",
        "• **Circumvention**: Bypass paywalls, access controls, usage limits, or security measures without authorization",
        "• **Reverse Engineering**: Decompile, disassemble, reverse engineer, or attempt to derive source code from Vayva's software (except as expressly permitted by law)",
        "• **Data Scraping**: Use automated tools (bots, scrapers, spiders) to extract data from Vayva without written permission",
        "• **Account Sharing**: Share your login credentials, sell or transfer your account, or allow unauthorized persons to access your account",
      ],
      type: "callout-important",
    },
    {
      heading: "5. Prohibited Activities - Intellectual Property Violations",
      content: [
        "You must NOT:",
        "• **Copyright Infringement**: Upload, share, or distribute content that infringes someone else's copyright",
        "• **Trademark Infringement**: Use trademarks, logos, or brand names without authorization in ways that cause consumer confusion",
        "• **Counterfeit Goods**: Sell or distribute counterfeit products or unauthorized replicas of branded items",
        "• **Patent Violation**: Sell products that violate valid patent rights",
        "• **Trade Secret Misappropriation**: Disclose or use confidential information belonging to others without authorization",
      ],
      type: "text",
    },
    {
      heading: "6. Messaging & Automation Standards",
      content: [
        "If you use Vayva's messaging automation tools, you must:",
        "• **Obtain Consent**: Only send messages to customers who have explicitly opted in to receive communications from you",
        "• **Provide Opt-Out**: Include clear unsubscribe/opt-out instructions in every marketing message",
        "• **Honor Preferences**: Respect customer communication preferences and remove unsubscribed users within 72 hours",
        "• **Accurate Sender Info**: Clearly identify yourself as the sender; do not use misleading headers or subject lines",
        "• **No Sensitive Data Collection**: Do not solicit passwords, credit card numbers, or other sensitive personal information via automated messages",
        "• **Frequency Limits**: Do not bombard customers with excessive messages (recommended: maximum 4 marketing messages per month per customer)",
      ],
      type: "text",
    },
    {
      heading: "7. Prohibited Items & Services",
      content: [
        "You may not sell or promote items listed in our separate Prohibited Items Policy, including but not limited to:",
        "• Illegal drugs, narcotics, controlled substances",
        "• Firearms, ammunition, explosives, weapons",
        "• Counterfeit currency, forged documents, stolen goods",
        "• Hazardous materials, radioactive substances",
        "• Human remains, body parts (unless legally donated for scientific research)",
        "• Live animals (except through approved breeders with proper documentation)",
        "• Prescription medications without appropriate pharmacy licensing",
        "See vayva.ng/legal/prohibited-items for the complete list.",
      ],
      type: "text",
    },
    {
      heading: "8. API & Developer Usage",
      content: [
        "If you use Vayva's APIs:",
        "• **Rate Limits**: Respect API rate limits; do not attempt to bypass throttling mechanisms",
        "• **Authorized Apps**: Only develop applications that comply with Vayva's API Terms of Service",
        "• **Data Protection**: Implement appropriate security measures to protect any data accessed via APIs",
        "• **No Resale**: Do not resell API access or create competing services using Vayva's APIs",
        "• **Attribution**: Provide appropriate attribution to Vayva when using API data in public displays",
      ],
      type: "text",
    },
    {
      heading: "9. Impersonation & Misrepresentation",
      content: [
        "You must NOT:",
        "• **Impersonate Vayva**: Claim to be Vayva employees, representatives, or official partners without written authorization",
        "• **Fake Reviews**: Post fake reviews, ratings, or testimonials for your own products or competitors' products",
        "• **Misleading Claims**: Make false claims about product capabilities, endorsements, certifications, or affiliations",
        "• **Bait-and-Switch**: Advertise products at one price/quality and deliver something different",
      ],
      type: "text",
    },
    {
      heading: "10. Enforcement & Consequences",
      content: [
        "Violation of this Acceptable Use Policy may result in:",
        "• **Warning**: First-time minor violations may result in a written warning",
        "• **Content Removal**: We may remove violating content without notice",
        "• **Temporary Suspension**: Repeated or serious violations may result in temporary account suspension pending investigation",
        "• **Permanent Termination**: Severe violations or pattern of abuse may result in permanent account termination",
        "• **Legal Action**: We may report violations to law enforcement and pursue civil remedies where appropriate",
        "• **Financial Liability**: You may be held liable for damages caused by your violations, including legal fees",
        "",
        "We reserve the right to investigate violations and take appropriate action at our sole discretion. This policy does not limit any legal rights or remedies available to Vayva under law.",
      ],
      type: "callout-important",
    },
    {
      heading: "11. Reporting Violations",
      content: [
        "If you become aware of any violation of this policy, please report it immediately to support@vayva.ng with subject line 'Acceptable Use Violation'. Include:",
        "• The user/store URL involved",
        "• Description of the violation",
        "• Screenshots or evidence if available",
        "• Your contact information (we keep reporters confidential)",
        "",
        "We take all reports seriously and will investigate promptly. Thank you for helping keep Vayva safe for everyone.",
      ],
      type: "text",
    },
    {
      heading: "12. Updates to This Policy",
      content: [
        "We may update this Acceptable Use Policy from time to time. Material changes will be communicated via email or in-app notification at least 7 days before they take effect. Continued use of Vayva after changes constitutes acceptance of the updated policy.",
        "Last updated: March 18, 2026.",
      ],
      type: "text",
    },
  ],
};
