/**
 * ACCESSIBILITY STATEMENT
 * 
 * WCAG 2.1 AA conformance commitment
 * Required for: Public sector clients, EU market, disability discrimination prevention
 */

import type { LegalDocument } from "../types";

export const accessibilityStatement: LegalDocument = {
  slug: "accessibility-statement",
  title: "Accessibility Statement",
  lastUpdated: "March 19, 2026",
  version: "1.0",
  summary:
    "Vayva's commitment to digital accessibility for people with disabilities and our progress toward WCAG 2.1 AA conformance.",
  sections: [
    {
      heading: "Our Commitment",
      content: [
        "Vayva is committed to ensuring digital accessibility for people with disabilities. We are continually improving the user experience for everyone and applying the relevant accessibility standards to ensure we provide an inclusive environment for all users.",
        "",
        "Vision: Every merchant, regardless of ability, should be able to build and manage their online business successfully on Vayva.",
        "",
        "Mission: Achieve and maintain WCAG 2.1 Level AA conformance across all Vayva platforms by December 31, 2026.",
      ],
      type: "text",
    },
    {
      heading: "Conformance Status",
      content: [
        "Web Content Accessibility Guidelines (WCAG) 2.1 Level AA",
        "",
        "Current Status: Partially Conformant",
        "",
        "Partially conformant means some parts of our content do not yet fully meet accessibility standards. We are actively working to address these issues.",
        "",
        "Target Date for Full Conformance: December 31, 2026",
        "",
        "What This Means:",
        "• We are committed to making our platform accessible to people with disabilities",
        "• We follow WCAG 2.1 guidelines as the international standard",
        "• We regularly test with screen readers, keyboard navigation, and assistive technologies",
        "• We train our design and development teams on accessibility best practices",
        "• We include accessibility requirements in our product roadmap and prioritization",
      ],
      type: "callout-important",
    },
    {
      heading: "Measures We Have Taken",
      content: [
        "FORMAL COMMITMENTS:",
        "• Accessibility integrated into company mission and values",
        "• Executive sponsor appointed (VP of Engineering)",
        "• Dedicated accessibility task force formed (Q1 2026)",
        "• Annual accessibility budget allocated",
        "",
        "DESIGN & DEVELOPMENT PRACTICES:",
        "• Accessibility requirements in product definition (Definition of Done)",
        "• Design system includes accessible components (colors, contrast, focus states)",
        "• Code review checklist includes accessibility criteria",
        "• Automated testing with axe-core and Lighthouse in CI/CD pipeline",
        "• Manual keyboard navigation testing before releases",
        "",
        "TRAINING & AWARENESS:",
        "• All developers completed WebAIM accessibility training (January 2026)",
        "• Designers trained in WCAG color contrast and focus management",
        "• Support team trained on assisting users with disabilities",
        "• Quarterly accessibility workshops and knowledge sharing sessions",
        "",
        "TESTING & VALIDATION:",
        "• Monthly automated accessibility audits",
        "• Quarterly manual testing with screen readers (NVDA, JAWS, VoiceOver)",
        "• User testing sessions with people who have disabilities (completed Q1 2026)",
        "• Third-party accessibility audit scheduled for Q3 2026",
      ],
      type: "definitions",
    },
    {
      heading: "Known Accessibility Issues",
      content: [
        "We are transparent about areas where we have not yet met full accessibility standards:",
        "",
        "IMAGES & MEDIA:",
        "• ⚠️ Some legacy product images missing alternative text",
        "• ⚠️ Icon-only buttons without aria-labels in older components",
        "• Status: Auto-generating alt text for images using AI (Q2 2026)",
        "• Timeline: 95% coverage by June 2026",
        "",
        "COLOR CONTRAST:",
        "• ⚠️ Some secondary text fails 4.5:1 contrast ratio (gray text on light backgrounds)",
        "• ⚠️ Chart colors in analytics dashboard insufficient contrast",
        "• Status: Updating design system color palette",
        "• Timeline: Complete by April 2026",
        "",
        "KEYBOARD NAVIGATION:",
        "• ⚠️ Complex dropdown menus require mouse interaction in some legacy features",
        "• ⚠️ Focus indicators not visible in high contrast mode on some pages",
        "• Status: Refactoring navigation components",
        "• Timeline: Complete by May 2026",
        "",
        "FORMS & INPUTS:",
        "• ⚠️ Some error messages not programmatically associated with form fields",
        "• ⚠️ Missing autocomplete attributes on shipping address forms",
        "• Status: Updating form validation library",
        "• Timeline: Complete by March 2026",
        "",
        "DYNAMIC CONTENT:",
        "• ⚠️ Live regions not announced properly for real-time notifications",
        "• ⚠️ Loading spinners missing aria-live announcements",
        "• Status: Implementing ARIA live regions across platform",
        "• Timeline: Complete by April 2026",
        "",
        "MOBILE ACCESSIBILITY:",
        "• ⚠️ Touch targets below 44x44 pixels in some mobile UI elements",
        "• ⚠️ Gesture-based interactions lack alternative controls",
        "• Status: Mobile app accessibility audit in progress",
        "• Timeline: Fixes by July 2026",
      ],
      type: "text",
    },
    {
      heading: "Technologies Relied Upon",
      content: [
        "Vayva relies on the following web technologies to achieve accessibility:",
        "",
        "• HTML5: Semantic structure, ARIA landmarks, form labels",
        "• CSS3: Visual styling, responsive design, reduced motion preferences",
        "• JavaScript (ES6+): Interactive functionality, keyboard event handling, ARIA updates",
        "• WAI-ARIA 1.2: Accessible rich internet applications (live regions, roles, states)",
        "• SVG: Scalable graphics with titles and descriptions",
        "",
        "Browsers & Assistive Technologies Tested:",
        "• Chrome + NVDA (Windows)",
        "• Firefox + JAWS (Windows)",
        "• Safari + VoiceOver (macOS, iOS)",
        "• Edge + Narrator (Windows)",
        "• Chrome + TalkBack (Android)",
        "• Safari + VoiceOver (iOS)",
        "",
        "**Not Yet Tested:**",
        "• Dragon NaturallySpeaking (voice recognition)",
        "• Switch devices for motor impairments",
        "• Screen readers on Linux (Orca)",
      ],
      type: "text",
    },
    {
      heading: "Compatibility",
      content: [
        "**FULLY COMPATIBLE WITH:**",
        "• Modern browsers (Chrome, Firefox, Safari, Edge) - last 2 versions",
        "• Screen readers: NVDA 2023+, JAWS 2022+, VoiceOver macOS/iOS latest",
        "• Keyboard-only navigation (Tab, Enter, Space, Arrow keys)",
        "• Browser zoom up to 200% without loss of functionality",
        "• High contrast mode (Windows) and Increase Contrast (macOS)",
        "• Mobile screen readers (VoiceOver iOS, TalkBack Android)",
        "",
        "**LIMITED COMPATIBILITY:**",
        "• Internet Explorer 11 (deprecated - no longer supported)",
        "• Legacy screen readers (pre-2020 versions)",
        "• Text-only browsers (Lynx) - visual layout not preserved",
        "",
        "**NOT YET COMPATIBLE:**",
        "• Voice control software (Dragon) - working on voice command support",
        "• Switch scanning devices - investigating compatibility improvements",
      ],
      type: "text",
    },
    {
      heading: "How to Report Accessibility Issues",
      content: [
        "**WE NEED YOUR FEEDBACK**",
        "",
        "If you encounter accessibility barriers while using Vayva, please contact us. We take all feedback seriously and will investigate your concerns.",
        "",
        "**EMAIL:**",
        "Send details to: accessibility@vayva.ng",
        "Subject line: 'Accessibility Issue'",
        "",
        "**PLEASE INCLUDE:**",
        "• The specific page or feature where you experienced the issue",
        "• What assistive technology you are using (screen reader, keyboard, etc.)",
        "• Your browser and operating system",
        "• Description of the problem and what you expected to happen",
        "• Screenshots or screen recordings (if possible)",
        "",
        "**ALTERNATIVE CONTACT:**",
        "If email is not accessible to you, call: +234-810-769-2393",
        "Ask for: Customer Support (mention you need accessibility assistance)",
        "",
        "**WHAT TO EXPECT:**",
        "• **Acknowledgment**: We will confirm receipt within 2 business days",
        "• **Assessment**: Our accessibility team will reproduce and evaluate the issue",
        "• **Response**: We will contact you within 5 business days with:",
        "  - Whether we can reproduce the issue",
        "  - Proposed workaround (if available)",
        "  - Estimated timeline for fix",
        "  - Alternative access method (if fix requires time)",
        "• **Resolution**: We will notify you when the issue is fixed",
        "• **Follow-up**: We may ask you to test the fix and confirm it works",
      ],
      type: "callout-important",
    },
    {
      heading: "Enforcement Procedure",
      content: [
        "**IF YOU ARE NOT SATISFIED WITH OUR RESPONSE:**",
        "",
        "You have the right to escalate accessibility complaints to external bodies:",
        "",
        "**IN NIGERIA:**",
        "• **Joint National Association of Persons with Disabilities (JONAPWD)**",
        "  Email: info@jonapwd.org",
        "  Phone: +234-803-XXX-XXXX",
        "",
        "• **National Commission for Persons with Disabilities (NCPWD)**",
        "  Email: info@ncpwd.gov.ng",
        "  Phone: +234-9-XXX-XXXX",
        "",
        "**INTERNATIONAL:**",
        "• If you are in the EU: Contact your national equality body",
        "• If you are in the UK: Equality and Human Rights Commission (EHRC)",
        "• If you are in the US: Department of Justice ADA Information Line",
        "",
        "**NOTE:** We encourage you to contact us first so we can resolve the issue directly. Most accessibility concerns can be addressed quickly through direct communication.",
      ],
      type: "text",
    },
    {
      heading: "Assessment Approach",
      content: [
        "**HOW WE EVALUATE ACCESSIBILITY:**",
        "",
        "Vayva uses a combination of approaches to assess accessibility:",
        "",
        "**SELF-ASSESSMENT:**",
        "• Internal testing by trained engineering and design teams",
        "• Automated scanning with axe-core, WAVE, and Lighthouse",
        "• Manual keyboard navigation testing",
        "• Color contrast analysis with Contrast Checker tools",
        "",
        "**EXTERNAL AUDIT (Planned):**",
        "• Third-party accessibility audit scheduled for Q3 2026",
        "• Comprehensive WCAG 2.1 AA evaluation by certified professionals",
        "• Detailed report with remediation plan",
        "• Follow-up testing after fixes implemented",
        "",
        "**ONGOING MONITORING:**",
        "• Monthly automated scans of critical user journeys",
        "• Quarterly manual testing with assistive technologies",
        "• Bi-annual user testing with people who have disabilities",
        "• Continuous monitoring of customer support tickets for accessibility issues",
      ],
      type: "text",
    },
    {
      heading: "Improvement Plans & Timeline",
      content: [
        "**Q1 2026 (January - March):**",
        "✅ Accessibility task force established",
        "✅ Team training completed",
        "✅ Form validation library updated (completed March 2026)",
        "",
        "**Q2 2026 (April - June):**",
        "⏳ Design system color palette updated for contrast compliance",
        "⏳ ARIA live regions implemented for dynamic content",
        "⏳ AI-generated alt text for product images (95% coverage)",
        "⏳ First user testing session with disabled participants",
        "",
        "**Q3 2026 (July - September):**",
        "⏳ Third-party accessibility audit",
        "⏳ Mobile accessibility improvements",
        "⏳ Keyboard navigation refactoring complete",
        "⏳ Voice control compatibility research",
        "",
        "**Q4 2026 (October - December):**",
        "⏳ Address third-party audit findings",
        "⏳ Final push for WCAG 2.1 AA conformance",
        "⏳ Documentation and VPAT (Voluntary Product Accessibility Template) creation",
        "⏳ **TARGET: Full WCAG 2.1 AA conformance by December 31, 2026**",
        "",
        "**BEYOND 2026:**",
        "• Maintain conformance through continuous testing",
        "• Explore emerging accessibility technologies (AI, AR/VR)",
        "• Contribute to open-source accessibility initiatives",
        "• Share learnings with broader tech community",
      ],
      type: "definitions",
    },
    {
      heading: "Product Roadmap Integration",
      content: [
        "**ACCESSIBILITY IS NOT AN AFTER THOUGHT**",
        "",
        "Accessibility is integrated into our product development lifecycle:",
        "",
        "**DISCOVERY PHASE:**",
        "• User research includes people with disabilities",
        "• Accessibility requirements gathered alongside functional requirements",
        "• Success metrics include accessibility KPIs",
        "",
        "**DESIGN PHASE:**",
        "• Wireframes reviewed for keyboard navigation flow",
        "• Color contrast checked in mockups",
        "• Focus states designed for interactive elements",
        "",
        "**DEVELOPMENT PHASE:**",
        "• Semantic HTML used throughout",
        "• ARIA attributes added where needed",
        "• Keyboard event handlers implemented",
        "• Automated accessibility tests in CI/CD",
        "",
        "**TESTING PHASE:**",
        "• Manual keyboard testing required before merge",
        "• Screen reader testing for critical flows",
        "• Accessibility acceptance criteria verified",
        "",
        "**RELEASE PHASE:**",
        "• Accessibility sign-off required for production deployment",
        "• Release notes include accessibility improvements",
        "• Known issues documented with workarounds",
      ],
      type: "text",
    },
    {
      heading: "Standards & Guidelines",
      content: [
        "**WE FOLLOW THESE STANDARDS:**",
        "",
        "• **WCAG 2.1 Level AA**: World Wide Web Consortium (W3C) standard",
        "  https://www.w3.org/TR/WCAG21/",
        "",
        "• **Section 508**: U.S. Rehabilitation Act (for government clients)",
        "  https://www.section508.gov/",
        "",
        "• **EN 301 549**: European accessibility standard (for EU market)",
        "  https://www.etsi.org/deliver/etsi_en/301500_301599/301549/",
        "",
        "• **ADA Title III**: Americans with Disabilities Act (for US market)",
        "  https://www.ada.gov/",
        "",
        "• **Disability Discrimination Act 1995**: UK law",
        "  https://www.equalityhumanrights.com/",
        "",
        "• **Discrimination Against Persons with Disabilities (Prohibition) Act**: Nigerian law",
        "  Signed into law January 2019",
      ],
      type: "text",
    },
    {
      heading: "Contact Us",
      content: [
        "**GENERAL INQUIRIES:**",
        "Email: accessibility@vayva.ng",
        "Phone: +234-810-769-2393",
        "Hours: 9am - 6pm West Africa Time (WAT), Monday - Friday",
        "",
        "**MAILING ADDRESS:**",
        "Vayva Technologies Ltd.",
        "Attn: Accessibility Team",
        "[Your Lagos Office Address]",
        "Lagos, Nigeria",
        "",
        "**RESPONSE TIME:**",
        "We aim to respond to all accessibility inquiries within 2 business days.",
        "",
        "**LANGUAGE:**",
        "This statement is available in English. For translations, contact support@vayva.ng.",
        "",
        "**LAST UPDATED:** March 19, 2026",
        "**NEXT REVIEW:** June 2026 (quarterly accessibility review)",
        "**VERSION:** 1.0",
      ],
      type: "text",
    },
  ],
};
