import type { LegalDocument } from "../types";

export const cookiePolicy: LegalDocument = {
  slug: "cookies",
  title: "Cookie Policy",
  lastUpdated: "March 18, 2026",
  version: "1.0",
  summary:
    "Comprehensive information about how we use cookies and similar technologies on Vayva, including your rights to control cookie usage.",
  sections: [
    {
      heading: "1. What Are Cookies",
      content: [
        "Cookies are small text files stored on your device (computer, smartphone, or tablet) when you visit our website. They help us remember your preferences, improve site performance, analyze usage, and provide personalized experiences.",
        "Similar technologies include web beacons, pixel tags, and local storage, which we collectively refer to as 'cookies' in this policy.",
      ],
      type: "text",
    },
    {
      heading: "2. Types of Cookies We Use",
      content: [
        "**ESSENTIAL COOKIES (Always Active - No Consent Required)**",
        "These cookies are necessary for the website to function and cannot be disabled:",
        "• Session Cookies: Expire when you close your browser; maintain your login session and shopping cart",
        "• Authentication Cookies: 30 days; keep you logged in securely",
        "• Security Cookies: 1 year; protect against CSRF attacks and verify user identity",
        "• Load Balancing Cookies: Session duration; distribute traffic across servers for performance",
        "",
        "**FUNCTIONAL COOKIES (Can Be Disabled)**",
        "These cookies remember your choices to provide enhanced features:",
        "• Language Preference: 2 years; remembers your selected language",
        "• Currency Selection: 1 year; displays prices in your preferred currency",
        "• Cart Contents: 30 days; saves items in your shopping cart between visits",
        "• Recently Viewed Items: 7 days; shows your browsing history for easy navigation",
        "",
        "**ANALYTICS COOKIES (Require Your Consent)**",
        "These cookies help us understand how you use our website:",
        "• Google Analytics (_ga, _gid, _gat): 26 months; tracks page views, session duration, bounce rates (you can opt-out: https://tools.google.com/dlpage/gaoptout)",
        "• Hotjar (_hjSession, _hjAbsoluteSessionInProgress): 365 days; heatmaps and user behavior analytics",
        "• Microsoft Clarity: 365 days; session recordings and usage analytics",
        "",
        "**MARKETING COOKIES (Require Your Consent)**",
        "These cookies are used to track visitors across websites:",
        "• Google Ads (_gcl_au, _gcl_aw): 540 days; measures ad performance and conversion tracking",
        "• Facebook Pixel (_fbp): 180 days; delivers targeted ads and measures ad performance",
        "• TikTok Pixel: 180 days; tracks conversions from TikTok ads",
        "• LinkedIn Insight Tag: 90 days; tracks conversions and retargeting for LinkedIn ads",
      ],
      type: "definitions",
    },
    {
      heading: "3. Third-Party Cookies",
      content: [
        "In addition to our own cookies, we use cookies from trusted third-party service providers:",
        "• **Google Ireland Limited** (Analytics & Ads): Data may be transferred to the US under Standard Contractual Clauses. Privacy Policy: https://policies.google.com/privacy",
        "• **Meta Platforms Ireland Limited** (Facebook Pixel): Joint controllers with Meta for event data. Privacy Policy: https://www.facebook.com/privacy/policy",
        "• **Hotjar Ltd** (Malta): Analytics and feedback tools. Privacy Policy: https://www.hotjar.com/legal/policies/privacy",
        "• **Microsoft Corporation** (Clarity & Ads): Analytics and advertising services. Privacy Policy: https://privacy.microsoft.com/privacystatement",
        "These third parties may combine the information we provide with other data they collect from your use of their services.",
      ],
      type: "text",
    },
    {
      heading: "4. How to Manage Cookies",
      content: [
        "**Browser Controls:**",
        "You can control and/ordelete cookies through your browser settings. Most browsers allow you to:",
        "• View and delete individual cookies",
        "• Block all cookies or third-party cookies",
        "• Clear cookies when you close the browser",
        "• Set preferences for specific websites",
        "",
        "**How to Change Cookie Settings in Popular Browsers:**",
        "• Chrome: Settings > Privacy and security > Cookies and other site data",
        "• Firefox: Options > Privacy & Security > Cookies and Site Data",
        "• Safari: Preferences > Privacy > Cookies and website data",
        "• Edge: Settings > Privacy, search, and services > Cookies",
        "• Opera: Settings > Advanced > Privacy & security > Cookies",
        "",
        "**Opt-Out of Specific Services:**",
        "• Google Analytics: https://tools.google.com/dlpage/gaoptout",
        "• Google Ads: https://adssettings.google.com/",
        "• Facebook: https://www.facebook.com/settings?tab=ads",
        "• Hotjar: https://www.hotjar.com/legal/compliance/opt-out",
        "• Network Advertising Initiative: http://www.networkadvertising.org/choices/",
        "• Your Online Choices (EU): http://www.youronlinechoices.com/",
        "",
        "**Important Note:** If you disable essential cookies, some parts of the website may not function properly. If you disable analytics or marketing cookies, we cannot improve your experience based on usage data.",
      ],
      type: "callout-important",
    },
    {
      heading: "5. Cookie Consent",
      content: [
        "When you first visit our website, we will ask for your consent to use non-essential cookies (analytics and marketing). You can:",
        "• **Accept All**: Consent to all cookies for personalized experience",
        "• **Reject All**: Only essential cookies will be used",
        "• **Customize**: Choose which categories of cookies to enable",
        "• **Withdraw Consent**: Change your cookie preferences at any time by clicking 'Cookie Settings' in the website footer",
        "Your consent is valid for 12 months, after which we will ask you to renew your preferences.",
      ],
      type: "text",
    },
    {
      heading: "6. International Data Transfers",
      content: [
        "Some cookies involve transfers of personal data outside the European Economic Area (EEA). We ensure appropriate safeguards are in place:",
        "• For US transfers: Standard Contractual Clauses approved by the European Commission",
        "• For other third countries: Adequacy decisions or Binding Corporate Rules",
        "Details of specific transfers are available in our Privacy Policy Section 7 (International Transfers).",
      ],
      type: "text",
    },
    {
      heading: "7. Updates to This Policy",
      content: [
        "We may update this Cookie Policy from time to time to reflect changes in technology, legislation, or our business operations. Material changes will be communicated to you via cookie banner or email notification.",
        "Last updated: March 18, 2026. Next review date: March 2027.",
      ],
      type: "text",
    },
    {
      heading: "8. Contact Us",
      content: [
        "For questions about our use of cookies, contact us at support@vayva.ng with subject line 'Cookie Policy Question'.",
      ],
      type: "text",
    },
  ],
};
