/**
 * DPA SCHEDULE 2: TECHNICAL AND ORGANIZATIONAL MEASURES
 * 
 * Required by: GDPR Article 32, UK GDPR Article 32
 * "Security of processing" - comprehensive security controls
 */

export const dpaSchedule2 = {
  title: "Schedule 2: Technical and Organizational Measures",
  subtitle: "Information Security Controls for Personal Data Protection",
  lastUpdated: "March 18, 2026",
  version: "1.0",
  
  introduction: [
    "Vayva implements comprehensive technical and organizational measures to ensure a level of security appropriate to the risk of processing personal data. These measures are aligned with ISO 27001, SOC 2 Type II, NIST Cybersecurity Framework, and industry best practices.",
  ],
  
  sections: [
    {
      heading: "1. Encryption & Cryptographic Controls",
      content: [
        "**ENCRYPTION IN TRANSIT:**",
        "• TLS 1.3 or higher enforced for all data transmissions",
        "• Strong cipher suites only (AES-256-GCM, ChaCha20-Poly1305)",
        "• Perfect Forward Secrecy (PFS) enabled on all endpoints",
        "• HSTS (HTTP Strict Transport Security) implemented with preload",
        "• Certificate pinning for mobile applications",
        "• Automatic renewal of SSL/TLS certificates (Let's Encrypt, DigiCert)",
        "",
        "**ENCRYPTION AT REST:**",
        "• AES-256 encryption for all sensitive data at rest",
        "• Database-level encryption for PII (Personally Identifiable Information)",
        "• File storage encryption (AWS S3 SSE-S3 or SSE-KMS)",
        "• Backup encryption with separate key management",
        "• Full disk encryption on all servers and workstations",
        "",
        "**KEY MANAGEMENT:**",
        "• Hardware Security Modules (HSMs) for key storage (AWS KMS, Azure Key Vault)",
        "• Automatic key rotation every 90 days",
        "• Separation of duties: key custodians ≠ data operators",
        "• Multi-party authorization required for key access",
        "• Audit logs for all cryptographic operations",
        "• Compliance with FIPS 140-2 Level 3 for HSMs",
      ],
      type: "definitions" as const,
    },
    
    {
      heading: "2. Access Control & Authentication",
      content: [
        "**ROLE-BASED ACCESS CONTROL (RBAC):**",
        "• Principle of least privilege strictly enforced",
        "• Need-to-know basis for all data access",
        "• Segregation of duties between development, staging, production",
        "• Regular access reviews (quarterly for privileged users, annually for all)",
        "• Immediate access revocation upon termination",
        "",
        "**MULTI-FACTOR AUTHENTICATION (MFA):**",
        "• MFA mandatory for all employee accounts",
        "• TOTP (Time-based One-Time Password) via authenticator apps",
        "• Hardware security keys (YubiKey) for privileged access",
        "• SMS-based MFA prohibited for high-privilege accounts",
        "• MFA bypass requires CISO approval + compensating controls",
        "",
        "**PRIVILEGED ACCESS MANAGEMENT (PAM):**",
        "• Just-in-time (JIT) access for production systems",
        "• Time-limited credentials (maximum 8-hour sessions)",
        "• All privileged sessions recorded and audited",
        "• Break-glass procedures for emergencies with post-incident review",
        "• Separate admin accounts for daily use vs administrative tasks",
        "",
        "**PASSWORD POLICY:**",
        "• Minimum 14 characters for employees, 12 for users",
        "• Complexity requirements (uppercase, lowercase, numbers, symbols)",
        "• Password history (cannot reuse last 12 passwords)",
        "• Maximum password age: 90 days for employees",
        "• Account lockout after 5 failed attempts (30-minute duration)",
        "• Breached password detection (Have I Been Pwned integration)",
      ],
      type: "text" as const,
    },
    
    {
      heading: "3. Network Security",
      content: [
        "**FIREWALLS & SEGMENTATION:**",
        "• Enterprise-grade next-generation firewalls (Palo Alto, Fortinet)",
        "• Network segmentation: DMZ, application tier, database tier",
        "• Micro-segmentation within cloud environments (AWS Security Groups, NSGs)",
        "• Air-gapped backup networks isolated from production",
        "• VLAN separation for different data sensitivity levels",
        "",
        "**INTRUSION DETECTION & PREVENTION:**",
        "• IDS/IPS systems monitoring all network traffic (Snort, Suricata)",
        "• Signature-based and anomaly-based detection",
        "• Automated blocking of known malicious IPs",
        "• Integration with threat intelligence feeds",
        "• Real-time alerts to Security Operations Center (SOC)",
        "",
        "**DDoS MITIGATION:**",
        "• Cloudflare Pro/AWS Shield Advanced protection",
        "• Automatic traffic scrubbing during attacks",
        "• Rate limiting at edge locations",
        "• Geographic blocking for high-risk regions",
        "• Incident response playbook for DDoS events",
        "",
        "**WEB APPLICATION FIREWALL (WAF):**",
        "• OWASP ModSecurity Core Rule Set deployed",
        "• Protection against SQL injection, XSS, CSRF, RCE",
        "• Custom rules for Vayva-specific threats",
        "• Virtual patching for zero-day vulnerabilities",
        "• Positive security model (allow-list approach for critical endpoints)",
      ],
      type: "callout-important" as const,
    },
    
    {
      heading: "4. Application Security",
      content: [
        "**SECURE SOFTWARE DEVELOPMENT LIFECYCLE (SDLC):**",
        "• Security requirements defined at project inception",
        "• Threat modeling for high-risk features",
        "• Secure coding training for all developers (annual refresh)",
        "• Code review mandatory before merge (minimum 2 approvers)",
        "• Security champion in each engineering team",
        "",
        "**STATIC & DYNAMIC TESTING:**",
        "• SAST (Static Application Security Testing) in CI/CD pipeline (SonarQube, Checkmarx)",
        "• DAST (Dynamic Application Security Testing) before production releases (OWASP ZAP, Burp Suite)",
        "• Software Composition Analysis (SCA) for dependency vulnerabilities (Snyk, Dependabot)",
        "• Container scanning for Docker images (Trivy, Clair)",
        "• Infrastructure as Code scanning (Terraform, CloudFormation) with Checkov, tfsec",
        "",
        "**PENETRATION TESTING:**",
        "• Annual penetration tests by CREST-certified third parties",
        "• Quarterly internal penetration tests by security team",
        "• Bug bounty program via HackerOne or Bugcrowd",
        "• Red team exercises annually",
        "• Vulnerability disclosure policy with safe harbor provisions",
        "",
        "**VULNERABILITY MANAGEMENT:**",
        "• Critical vulnerabilities: Remediated within 72 hours",
        "• High vulnerabilities: Remediated within 7 days",
        "• Medium vulnerabilities: Remediated within 30 days",
        "• Low vulnerabilities: Remediated within 90 days or next release cycle",
        "• Emergency patching process for zero-day exploits",
      ],
      type: "text" as const,
    },
    
    {
      heading: "5. Data Protection & Privacy Engineering",
      content: [
        "**DATA MINIMIZATION:**",
        "• Only necessary data collected for specified purposes",
        "• Purpose limitation enforced at application layer",
        "• Field-level access controls for sensitive attributes",
        "• Data masking in non-production environments",
        "",
        "**PSEUDONYMISATION & ANONYMISATION:**",
        "• Customer IDs used instead of names in analytics",
        "• IP addresses truncated for privacy-preserving analytics",
        "• Differential privacy techniques for aggregate statistics",
        "• k-anonymity ensured for released datasets (k≥15)",
        "",
        "**DATA LOSS PREVENTION (DLP):**",
        "• Endpoint DLP agents on all corporate devices",
        "• Email DLP scanning for sensitive data exfiltration",
        "• Cloud Access Security Broker (CASB) for SaaS applications",
        "• USB device control and encryption requirement",
        "• Watermarking for confidential documents",
        "",
        "**BACKUP & RECOVERY:**",
        "• Automated daily backups with 30-day retention",
        "• Geo-redundant backup storage (minimum 2 regions)",
        "• Immutable backups (WORM - Write Once Read Many)",
        "• Quarterly backup restoration tests",
        "• Recovery Time Objective (RTO): 4 hours for critical systems",
        "• Recovery Point Objective (RPO): 1 hour maximum data loss",
      ],
      type: "definitions" as const,
    },
    
    {
      heading: "6. Incident Response & Business Continuity",
      content: [
        "**COMPUTER SECURITY INCIDENT RESPONSE TEAM (CSIRT):**",
        "• 24/7 on-call rotation for security incidents",
        "• Defined roles: Incident Commander, Communications Lead, Technical Lead",
        "• Escalation matrix with contact details maintained",
        "• War room procedures for critical incidents",
        "",
        "**INCIDENT DETECTION & TRIAGE:**",
        "• SIEM (Security Information and Event Management) aggregation (Splunk, ELK Stack)",
        "• Correlation rules for common attack patterns",
        "• User and Entity Behavior Analytics (UEBA) for insider threats",
        "• Automated alerting based on severity thresholds",
        "",
        "**INCIDENT RESPONSE PROCESS:**",
        "• Detection → Containment → Eradication → Recovery → Lessons Learned",
        "• Playbooks for common scenarios (data breach, ransomware, DDoS, insider threat)",
        "• Forensic evidence preservation procedures",
        "• Legal and regulatory notification workflows (72-hour GDPR breach notification)",
        "• Post-incident review within 2 weeks of resolution",
        "",
        "**BUSINESS CONTINUITY & DISASTER RECOVERY:**",
        "• Business Impact Analysis (BIA) updated annually",
        "• Disaster Recovery Plan documented and tested",
        "• Hot standby environment in secondary region",
        "• Annual disaster recovery drill with executive participation",
        "• Succession planning for critical roles",
      ],
      type: "text" as const,
    },
    
    {
      heading: "7. Physical Security",
      content: [
        "**OFFICE SECURITY:**",
        "• Badge access control with PIN codes",
        "• Visitor registration and escort requirements",
        "• CCTV monitoring of entrances and sensitive areas",
        "• Alarm systems connected to security company",
        "• Clean desk policy enforced",
        "• Secure disposal bins for confidential documents",
        "",
        "**DATA CENTER SECURITY (Cloud Providers):**",
        "• AWS/Azure/GCP certified data centers",
        "• Biometric access controls (fingerprint, retina scan)",
        "• 24/7 security guards with background checks",
        "• Mantrap entry systems",
        "• Environmental controls (fire suppression, temperature, humidity)",
        "• Uninterruptible Power Supply (UPS) and generators",
        "",
        "**DEVICE SECURITY:**",
        "• Full disk encryption mandatory on all laptops",
        "• Mobile Device Management (MDM) for remote wipe capability",
        "• Automatic screen lock after 5 minutes of inactivity",
        "• Prohibition on rooting/jailbreaking devices",
        "• Asset tagging and inventory tracking",
      ],
      type: "callout-important" as const,
    },
    
    {
      heading: "8. Organizational Measures",
      content: [
        "**GOVERNANCE & ACCOUNTABILITY:**",
        "• Board-level Risk Committee overseeing security",
        "• Chief Information Security Officer (CISO) reporting to CEO",
        "• Data Protection Officer (DPO) appointed (GDPR requirement)",
        "• Security policies reviewed and approved annually",
        "• Risk register maintained and updated quarterly",
        "",
        "**POLICIES & PROCEDURES:**",
        "• Information Security Policy (master document)",
        "• Acceptable Use Policy for employees and contractors",
        "• Data Classification and Handling Policy",
        "• Access Control Policy",
        "• Incident Response Policy",
        "• Business Continuity and Disaster Recovery Policy",
        "• Vendor Risk Management Policy",
        "• Secure Development Policy",
        "",
        "**TRAINING & AWARENESS:**",
        "• Mandatory security awareness training for all employees (annual)",
        "• Role-based training (developers, support, finance)",
        "• Phishing simulation exercises quarterly",
        "• Security champions program in each department",
        "• New hire security orientation",
        "• Exit interviews reinforcing confidentiality obligations",
        "",
        "**COMPLIANCE & AUDIT:**",
        "• Annual SOC 2 Type II audit",
        "• ISO 27001 certification maintained",
        "• PCI DSS Level 1 compliance for payment processing",
        "• Internal audits quarterly",
        "• External audits annually by Big Four firm",
        "• Regulatory examinations cooperation procedures",
      ],
      type: "text" as const,
    },
    
    {
      heading: "9. Subprocessor Management",
      content: [
        "**SUBPROCESSOR DUE DILIGENCE:**",
        "• Security questionnaires for all new subprocessors",
        "• Third-party risk assessment based on data sensitivity",
        "• On-site audits for critical subprocessors (annual)",
        "• SOC 2 Type II or ISO 27001 certification required where available",
        "",
        "**CONTRACTUAL SAFEGUARDS:**",
        "• Data Processing Agreements with all subprocessors",
        "• Standard Contractual Clauses for international transfers",
        "• Right to audit clauses included",
        "• Breach notification requirements (24-hour notice to Vayva)",
        "• Termination rights for material security breaches",
        "",
        "**ONGOING MONITORING:**",
        "• Annual reassessment of critical subprocessors",
        "• Continuous monitoring via Security Rating Services (BitSight, SecurityScorecard)",
        "• Public subprocessor list maintained at vayva.ng/subprocessors",
        "• 30-day notice for new subprocessor additions (objection period)",
      ],
      type: "definitions" as const,
    },
    
    {
      heading: "10. Testing & Assurance",
      content: [
        "**CONTROL TESTING:**",
        "• Annual penetration testing (external)",
        "• Quarterly vulnerability scans (internal)",
        "• Monthly access reviews",
        "• Weekly backup restoration tests (sampled)",
        "• Daily log reviews (automated + manual sampling)",
        "",
        "**CERTIFICATIONS & ATTESTATIONS:**",
        "• SOC 2 Type II report (updated annually)",
        "• ISO 27001 certificate (triennial audit with surveillance visits)",
        "• PCI DSS Level 1 Attestation of Compliance (annual)",
        "• Cyber insurance coverage ($5M minimum)",
        "",
        "**METRICS & REPORTING:**",
        "• Mean Time to Detect (MTTD): Target <1 hour",
        "• Mean Time to Respond (MTTR): Target <4 hours",
        "• Patch compliance rate: >95% within SLA",
        "• Phishing click rate: <5% (target)",
        "• Security training completion: 100%",
        "• Quarterly security metrics reported to Board",
      ],
      type: "text" as const,
    },
  ],
};
