/**
 * DPA SCHEDULE 1: DETAILS OF PROCESSING
 * 
 * Required by: GDPR Article 28(3), UK GDPR Article 28(3)
 * This schedule forms an integral part of the Data Processing Agreement
 */

export const dpaSchedule1 = {
  title: "Schedule 1: Details of Processing",
  lastUpdated: "March 18, 2026",
  version: "1.0",
  
  sections: [
    {
      heading: "1. Nature and Purpose of Processing",
      content: [
        "Vayva processes personal data to provide e-commerce platform services including:",
        "",
        "**CORE PLATFORM SERVICES:**",
        "• Online store creation and management tools",
        "• Product catalog management and inventory tracking",
        "• Order processing and fulfillment workflows",
        "• Payment gateway integration and transaction processing",
        "• Customer relationship management (CRM) tools",
        "• Shipping and delivery coordination",
        "• Analytics and business intelligence dashboards",
        "• Marketing automation (email campaigns, SMS notifications)",
        "• Multi-channel sales (web, mobile, social media integration)",
        "",
        "**SUPPORT & OPERATIONS:**",
        "• Customer support ticketing and live chat",
        "• Fraud detection and prevention systems",
        "• Compliance monitoring (KYC, AML, sanctions screening)",
        "• Platform security monitoring and incident response",
        "• System maintenance, backups, and disaster recovery",
        "• Quality assurance and service improvement",
        "",
        "**BUSINESS OPERATIONS:**",
        "• Billing, invoicing, and subscription management",
        "• Account verification and identity validation",
        "• Regulatory reporting and legal compliance",
        "• Business analytics and performance metrics",
        "• Communication with merchants (updates, announcements, policy changes)",
      ],
      type: "definitions" as const,
    },
    
    {
      heading: "2. Categories of Data Subjects",
      content: [
        "**MERCHANT ACCOUNT HOLDERS:**",
        "• Individual entrepreneurs, sole proprietors",
        "• Business owners, directors, shareholders (>25% ownership)",
        "• Authorized employees and team members with platform access",
        "• Contractors and agents acting on behalf of merchants",
        "",
        "**MERCHANT CUSTOMERS (END CONSUMERS):**",
        "• Individuals purchasing goods/services from merchant storefronts",
        "• Website visitors browsing merchant stores",
        "• Newsletter subscribers and marketing contacts",
        "• Support ticket submitters",
        "",
        "**PLATFORM USERS & VISITORS:**",
        "• Vayva website visitors (marketing site, blog, documentation)",
        "• Trial users exploring platform features",
        "• Job applicants submitting applications",
        "• Vendor and supplier contacts",
        "",
        "**SUPPORT & SERVICE CONTACTS:**",
        "• Individuals contacting Vayva support",
        "• Security researchers reporting vulnerabilities",
        "• Legal and regulatory authority contacts",
        "• Media and press inquiries",
      ],
      type: "text" as const,
    },
    
    {
      heading: "3. Categories of Personal Data",
      content: [
        "**IDENTITY DATA:**",
        "• Full name, username, user ID",
        "• Date of birth, nationality",
        "• Government identifiers (NIN, BVN, passport number)",
        "• Tax identification numbers (TIN)",
        "• Business registration numbers (CAC)",
        "• Profile photographs, signature images",
        "",
        "**CONTACT DATA:**",
        "• Email addresses (personal and business)",
        "• Phone numbers (mobile, landline)",
        "• Physical addresses (residential, business, shipping)",
        "• Social media handles and profiles",
        "",
        "**FINANCIAL DATA:**",
        "• Bank account numbers, sort codes",
        "• Payment card details (processed via PCI-DSS compliant providers)",
        "• Transaction history, payment records",
        "• Credit information, credit scores",
        "• Payout details, commission structures",
        "• Tax records, VAT numbers",
        "",
        "**COMMERCIAL DATA:**",
        "• Product listings, descriptions, pricing",
        "• Inventory levels, stock movements",
        "• Sales records, order history",
        "• Customer reviews, ratings, feedback",
        "• Supplier and vendor information",
        "• Contracts, agreements, terms of service acceptances",
        "",
        "**TECHNICAL DATA:**",
        "• IP addresses, MAC addresses",
        "• Browser type, version, language",
        "• Operating system, device type",
        "• Login timestamps, session duration",
        "• Device fingerprints, unique device identifiers",
        "• Geolocation data (GPS, WiFi triangulation)",
        "• Cookie identifiers, advertising IDs",
        "",
        "**USAGE DATA:**",
        "• Pages visited, features used",
        "• Click patterns, scroll behavior",
        "• Search queries, filter selections",
        "• Time spent on pages, navigation paths",
        "• Conversion events, goal completions",
        "• Error logs, crash reports",
        "",
        "**PROFILE DATA:**",
        "• Account preferences, settings",
        "• Marketing communication preferences",
        "• Language and currency preferences",
        "• Purchase history, spending patterns",
        "• Wishlist items, saved products",
        "• Loyalty program memberships",
        "",
        "**SPECIAL CATEGORY DATA (Only if voluntarily provided):**",
        "• Health data (for accessibility accommodations)",
        "• Biometric data (facial recognition for identity verification)",
        "• Trade union membership (via CAC documents)",
        "",
        "**WE DO NOT INTENTIONALLY COLLECT:**",
        "• Racial or ethnic origin",
        "• Political opinions",
        "• Religious or philosophical beliefs",
        "• Sexual orientation",
        "• Criminal convictions (except via background checks where legally permitted)",
      ],
      type: "definitions" as const,
    },
    
    {
      heading: "4. Duration and Frequency of Processing",
      content: [
        "**DURATION:**",
        "Processing continues for the duration of the Merchant's use of Vayva services plus statutory retention periods:",
        "",
        "• **Active Accounts**: Indefinitely while account remains active",
        "• **Closed Accounts**: 7 years after account closure (tax/AML requirements)",
        "• **Prospective Customers**: 2 years from last contact or until consent withdrawn",
        "• **Support Tickets**: 3 years from ticket resolution",
        "• **Marketing Lists**: Until consent withdrawal or 2 years from last engagement",
        "• **Analytics Data**: 26 months from collection (Google Analytics standard)",
        "• **Security Logs**: 12 months from generation",
        "• **Backup Copies**: 90 days after primary data deletion",
        "",
        "**FREQUENCY:**",
        "• **Real-time**: Authentication, fraud detection, payment processing",
        "• **Continuous**: Security monitoring, backup synchronization",
        "• **Daily**: Analytics aggregation, report generation",
        "• **Weekly**: Performance metrics, business intelligence updates",
        "• **Monthly**: Billing cycles, compliance reporting",
        "• **Annually**: Data quality audits, retention reviews",
      ],
      type: "text" as const,
    },
    
    {
      heading: "5. Specific Processing Operations",
      content: [
        "**ACCOUNT ONBOARDING:**",
        "• Collect identity and business verification data",
        "• Perform KYC/AML checks via Paystack (BVN) and manual review (as required)",
        "• Validate CAC registration documents",
        "• Screen against sanctions lists (UN, EU, OFAC)",
        "• Risk scoring and due diligence assessment",
        "",
        "**PAYMENT PROCESSING:**",
        "• Transmit payment data to PCI-DSS compliant processors",
        "• Verify bank account ownership for payouts",
        "• Calculate and remit applicable taxes (VAT, withholding tax)",
        "• Generate invoices and receipts",
        "• Process refunds and chargebacks",
        "",
        "**ORDER FULFILLMENT:**",
        "• Transmit customer shipping details to logistics partners",
        "• Track delivery status and update order records",
        "• Manage returns and exchange workflows",
        "• Coordinate with third-party delivery services",
        "",
        "**FRAUD PREVENTION:**",
        "• Analyze transaction patterns for anomalies",
        "• Cross-reference known fraud databases",
        "• Implement machine learning fraud detection models",
        "• Manual review of high-risk transactions",
        "• Report suspicious activity to authorities when required",
        "",
        "**MARKETING & ANALYTICS:**",
        "• Send promotional emails (with consent)",
        "• Display personalized product recommendations",
        "• Conduct A/B testing on features and UI elements",
        "• Generate aggregate usage statistics",
        "• Share anonymized insights with merchants",
        "",
        "**SECURITY OPERATIONS:**",
        "• Monitor login attempts for unauthorized access",
        "• Detect and block DDoS attacks",
        "• Scan for malware and malicious code uploads",
        "• Investigate security incidents and data breaches",
        "• Maintain audit trails for compliance purposes",
      ],
      type: "text" as const,
    },
    
    {
      heading: "6. Geographic Scope of Processing",
      content: [
        "**PRIMARY PROCESSING LOCATIONS:**",
        "• Nigeria (Lagos) - Primary operations, customer support, compliance",
        "• Cloud Infrastructure - Vercel edge + self-managed VPS / hosting provider data centers (region: as deployed, typically West Africa or EU where available)",
        "",
        "**DATA CENTER LOCATIONS:**",
        "Processing may occur in any jurisdiction where Vayva or its subprocessors maintain facilities, including but not limited to:",
        "• European Economic Area (Ireland, Netherlands, Germany, France)",
        "• United Kingdom (London)",
        "• United States (e.g. Vercel / US-based subprocessors per subprocessor list)",
        "• Regional VPS or provider facilities as documented in deployment runbooks",
        "• Nigeria (local hosting providers)",
        "",
        "**CROSS-BORDER TRANSFERS:**",
        "Data may be transferred between these jurisdictions for:",
        "• Centralized platform operations and maintenance",
        "• Global customer support (24/7 coverage across time zones)",
        "• Disaster recovery and business continuity",
        "• Load balancing and performance optimization",
        "• Compliance with local data residency requirements",
        "",
        "All transfers are governed by Standard Contractual Clauses (SCCs), Binding Corporate Rules (BCRs), or adequacy decisions as documented in Schedule 3 (International Transfer Mechanisms).",
      ],
      type: "callout-important" as const,
    },
  ],
};
