import { LegalDocument } from "../types";

export const kycExplainer: LegalDocument = {
  slug: "kyc-explainer",
  title: "KYC & Identity Verification",
  lastUpdated: "March 18, 2026",
  version: "1.0",
  summary: "Comprehensive guide to our identity and business verification process, including timelines, document requirements, and data protection measures.",
  sections: [
    {
      heading: "1. Why Verification Is Required",
      content: [
        "We verify identity and business details to:",
        "• **Protect You**: Prevent unauthorized access to your account and funds",
        "• **Protect Customers**: Ensure merchants are legitimate businesses that will deliver as promised",
        "• **Prevent Fraud**: Detect and deter money laundering, terrorist financing, and financial crime",
        "• **Comply with Law**: Meet regulatory obligations under Nigeria Money Laundering Act, CBN Anti-Money Laundering Guidelines, and international AML/CFT standards",
        "• **Enable Payments**: Payment processors (Paystack, banks) require verified merchant identities",
      ],
      type: "callout-important",
    },
    {
      heading: "2. What We Request",
      content: [
        "**FOR INDIVIDUAL MERCHANTS:**",
        "• Full legal name (as it appears on government ID)",
        "• Date of birth",
        "• Residential address (utility bill or bank statement required)",
        "• Phone number (verified via SMS)",
        "• Email address (verified via confirmation link)",
        "• NIN (National Identification Number) - for Nigerian residents",
        "• BVN (Bank Verification Number) - for Nigerian bank account holders",
        "• Government-issued photo ID (International Passport, Driver's License, or National ID Card)",
        "",
        "**FOR BUSINESS MERCHANTS:**",
        "• All individual verification for business owners/directors with >25% ownership",
        "• CAC (Corporate Affairs Commission) registration documents",
        "• Certificate of Incorporation",
        "• Memorandum & Articles of Association",
        "• Tax Identification Number (TIN)",
        "• Business address verification",
        "• Utility bill in business name",
        "",
        "**ADDITIONAL VERIFICATION (Risk-Based):**",
        "• Source of funds documentation (bank statements, payslips)",
        "• Proof of business activity (invoices, contracts, website)",
        "• Enhanced due diligence for high-value transactions (>₦5M monthly)",
      ],
      type: "definitions",
    },
    {
      heading: "3. How Verification Works",
      content: [
        "**STEP 1: SUBMISSION**",
        "You submit verification documents through your Merchant Dashboard under Settings → Verification. Documents are uploaded securely via encrypted connection.",
        "",
        "**STEP 2: AUTOMATED CHECKS (Instant - 5 minutes)**",
        "• **NIN Verification**: Via YouVerify API - instant validation against NIMC database",
        "• **BVN Verification**: Via Paystack Identity Check - instant validation against NIBSS database",
        "• **Liveness Detection**: Facial recognition to match selfie with ID photo",
        "• **Document Authenticity**: AI scans for forgery indicators (font consistency, security features, tampering)",
        "",
        "**STEP 3: MANUAL REVIEW (If Required)**",
        "• **CAC Documents**: Ops Console team reviews within 2-5 business days",
        "• **Address Verification**: Cross-check utility bills with public records",
        "• **Enhanced Due Diligence**: Compliance team reviews high-risk merchants",
        "",
        "**STEP 4: DECISION**",
        "• **Approved**: Full platform access, withdrawals enabled immediately",
        "• **Pending**: Additional documents requested via email",
        "• **Rejected**: Explanation provided; you may reapply with corrected documents",
      ],
      type: "text",
    },
    {
      heading: "4. Verification Timelines",
      content: [
        "**STANDARD VERIFICATION:**",
        "• NIN check: Instant (typically <5 minutes during business hours)",
        "• BVN check: Instant to 24 hours (depends on bank network availability)",
        "• ID document + selfie: 1-2 business days",
        "• Address verification: 1-3 business days",
        "",
        "**BUSINESS VERIFICATION:**",
        "• CAC document review: 2-5 business days",
        "• Director verification: Same day as individual verification",
        "• Full business approval: 3-7 business days total",
        "",
        "**ENHANCED DUE DILIGENCE:**",
        "• High-volume merchants (>₦10M monthly): 5-10 business days",
        "• Politically Exposed Persons (PEPs): 10-15 business days",
        "• Complex corporate structures: Case-by-case timeline",
        "",
        "**DELAYS MAY OCCUR IF:**",
        "• Documents are unclear, expired, or incomplete",
        "• Name mismatches between documents",
        "• System outages at verification providers (YouVerify, Paystack, NIBSS)",
        "• Public holidays or weekends",
        "",
        "We'll notify you via email if verification takes longer than expected.",
      ],
      type: "callout-important",
    },
    {
      heading: "5. Document Requirements",
      content: [
        "**ACCEPTABLE FORMATS:**",
        "• Color scans or high-quality photos (minimum 300 DPI)",
        "• PDF, JPG, PNG formats only",
        "• Maximum file size: 5MB per document",
        "• All four corners of document visible",
        "• Text must be clear and readable",
        "",
        "**NOT ACCEPTED:**",
        "• Black and white copies",
        "• Blurry, dark, or glare-obscured photos",
        "• Expired documents (except old addresses on utility bills)",
        "• Screenshots or digital photocopies",
        "• Documents with white-out or alterations",
        "",
        "**SELFIE REQUIREMENTS:**",
        "• Face clearly visible, no sunglasses or face coverings",
        "• Good lighting (natural light preferred)",
        "• Neutral background",
        "• Hold ID next to face for comparison",
        "• No filters or beauty mode enhancements",
      ],
      type: "text",
    },
    {
      heading: "6. Common Rejection Reasons",
      content: [
        "**DOCUMENT ISSUES:**",
        "• Expired ID or passport",
        "• Student ID, work ID (not government-issued)",
        "• Damaged or worn ID with illegible text",
        "• Foreign IDs without Nigerian residency permit",
        "",
        "**NAME MISMATCHES:**",
        "• NIN shows 'Mohammed' but ID shows 'Muhammad'",
        "• Maiden name on utility bill vs married name on ID",
        "• Nicknames vs legal names (e.g., 'Tunde' vs 'Olatundun')",
        "→ Solution: Provide marriage certificate, deed poll, or affidavit explaining discrepancy",
        "",
        "**ADDRESS ISSUES:**",
        "• Handwritten utility bills",
        "• Mobile phone bills (not accepted as proof of address)",
        "• Bank statements without official stamp",
        "• PO Box addresses (physical address required)",
        "",
        "**PHOTO ISSUES:**",
        "• Glare from flash photography",
        "• Fingers covering document edges",
        "• Tilted or cropped images",
        "• Shadows obscuring text",
      ],
      type: "callout-important",
    },
    {
      heading: "7. Appeal Process",
      content: [
        "If your verification is rejected:",
        "",
        "**STEP 1: REVIEW REJECTION EMAIL**",
        "We send detailed explanation of why verification failed and what documents are needed.",
        "",
        "**STEP 2: CORRECT THE ISSUE**",
        "• Obtain valid/correct documents",
        "• Retake photos following guidelines",
        "• Gather supporting documents for name changes",
        "",
        "**STEP 3: RESUBMIT**",
        "Upload corrected documents via dashboard or reply to rejection email with attachments.",
        "",
        "**STEP 4: EXPEDITED REVIEW**",
        "Re-submissions are prioritized and reviewed within 24-48 hours.",
        "",
        "**STEP 5: ESCALATION**",
        "If you believe rejection was erroneous, email compliance@vayva.ng with subject line 'Verification Appeal'. Include:",
        "• Your full name and account email",
        "• Rejection reason received",
        "• Why you believe it's incorrect",
        "• Any additional evidence",
        "",
        "Compliance team responds within 3 business days with final decision.",
      ],
      type: "text",
    },
    {
      heading: "8. Data Protection for Verification",
      content: [
        "**HOW WE PROTECT YOUR DATA:**",
        "• **Encryption**: All documents encrypted in transit (TLS 1.3) and at rest (AES-256)",
        "• **Access Controls**: Only authorized compliance team members can view verification documents",
        "• **Audit Logs**: Every document access is logged with user, timestamp, and purpose",
        "• **Retention**: Verification documents stored for 7 years after account closure (AML requirement), then securely deleted",
        "• **Third-Party Processing**: YouVerify and Paystack are NDPR-compliant, PCI DSS Level 1 certified",
        "",
        "**WHAT DATA IS SHARED:**",
        "• **With YouVerify**: Only NIN number and name for verification (we don't receive your full NIN record)",
        "• **With Paystack**: BVN and name for identity check (Paystack returns pass/fail only, not full BVN details)",
        "• **With Banks**: Account name matching for payout verification (no document sharing)",
        "• **With Regulators**: Only when legally required (court order, EFCC request, CBN examination)",
        "",
        "**YOUR RIGHTS:**",
        "• Request copy of all verification data we hold about you",
        "• Request correction of inaccurate information",
        "• Withdraw consent (note: this requires account closure as we cannot operate unverified accounts)",
        "• Lodge complaint with NDPC (Nigeria Data Protection Commission) if you believe rights violated",
      ],
      type: "callout-important",
    },
    {
      heading: "9. If You Do Not Verify",
      content: [
        "**WHAT YOU CAN DO WITHOUT VERIFICATION:**",
        "• Create account and set up store",
        "• List products and customize storefront",
        "• Browse marketplace and explore features",
        "• Access educational resources and support",
        "",
        "**RESTRICTIONS WITHOUT VERIFICATION:**",
        "• ❌ Cannot receive payments from customers",
        "• ❌ Cannot withdraw funds from Vayva balance",
        "• ❌ Cannot upgrade to paid plans",
        "• ❌ Limited to 5 product listings maximum",
        "• ❌ Cannot access advanced features (analytics, marketing tools, API)",
        "• ❌ Store marked as 'Unverified' (reduces customer trust)",
        "",
        "**DEADLINE:**",
        "You have 30 days from first sale to complete verification. After 30 days, unverified stores are suspended until verification is completed.",
      ],
      type: "text",
    },
    {
      heading: "10. Ongoing Verification Obligations",
      content: [
        "Verification is not a one-time event. You must:",
        "• Update expired documents within 30 days of expiry",
        "• Notify us of material changes (address, business structure, beneficial owners)",
        "• Respond to periodic review requests (annual for standard risk, quarterly for high risk)",
        "• Complete enhanced verification if transaction volumes increase significantly",
        "",
        "Failure to maintain current verification may result in temporary withdrawal holds or account restrictions.",
      ],
      type: "text",
    },
    {
      heading: "11. Contact & Support",
      content: [
        "**VERIFICATION SUPPORT:**",
        "Email: support@vayva.ng with subject line 'KYC Verification Help'",
        "Live Chat: Available in dashboard during business hours (9am-6pm WAT, Mon-Fri)",
        "Phone: +234-810-769-2393 (verification support only)",
        "",
        "**AVERAGE RESPONSE TIMES:**",
        "• Email: Within 24 hours",
        "• Live Chat: <5 minutes wait time",
        "• Phone: <10 minutes wait time",
        "",
        "We're here to help you successfully complete verification. Don't hesitate to reach out if you need assistance!",
      ],
      type: "text",
    },
  ],
};
