import type { LegalDocument } from "../types";

export const prohibitedItems: LegalDocument = {
  slug: "prohibited-items",
  title: "Prohibited Items Policy",
  lastUpdated: "March 18, 2026",
  version: "1.0",
  summary:
    "Comprehensive list of items, products, and activities that are strictly prohibited on the Vayva platform to ensure user safety and legal compliance.",
  sections: [
    {
      heading: "1. Introduction",
      content: [
        "Vayva maintains a comprehensive list of prohibited items to protect users, comply with applicable laws, and maintain platform integrity. Merchants found listing these items may have products removed and accounts suspended or terminated.",
        "This policy applies to all product listings, descriptions, images, digital products, and services offered through Vayva storefronts or marketplace.",
      ],
      type: "text",
    },
    {
      heading: "2. Absolutely Prohibited - Illegal & Dangerous Items",
      content: [
        "**DRUGS & DRUG PARAPHERNALIA**",
        "• Illegal drugs, narcotics, controlled substances without prescription",
        "• Drug paraphernalia (pipes, bongs, rolling papers marketed for illegal use)",
        "• Precursor chemicals used to manufacture illegal drugs",
        "• Synthetic cannabinoids ('Spice', 'K2'), research chemicals, designer drugs",
        "",
        "**WEAPONS & EXPLOSIVES**",
        "• Firearms (handguns, rifles, shotguns) and ammunition",
        "• Weapon parts, magazines, high-capacity clips",
        "• Explosives, dynamite, grenades, fireworks",
        "• Switchblades, ballistic knives, concealed weapons",
        "• Silencers, suppressors, short-barreled firearms",
        "• Military equipment (grenade launchers, rocket launchers)",
        "",
        "**COUNTERFEIT & STOLEN GOODS**",
        "• Counterfeit currency, forged banknotes, fake coins",
        "• Counterfeit luxury goods (bags, watches, jewelry)",
        "• Stolen merchandise, burglar tools, lock-picking devices",
        "• Forged documents (passports, driver's licenses, diplomas)",
        "• Academic cheating services (essay mills, exam proxies)",
        "",
        "**HAZARDOUS MATERIALS**",
        "• Radioactive materials, depleted uranium",
        "• Toxic chemicals (cyanide, ricin, sarin)",
        "• Asbestos, lead-based products",
        "• Compressed gases (propane tanks, aerosols) without proper certification",
        "• Flammable liquids (gasoline, lighter fluid, paint thinner)",
        "• Oxidizers, peroxides, bomb-making materials",
      ],
      type: "definitions",
    },
    {
      heading: "3. Regulated Items - License Required",
      content: [
        "**ALCOHOL & TOBACCO**",
        "• Alcoholic beverages (beer, wine, spirits) - requires liquor license",
        "• Tobacco products (cigarettes, cigars, loose tobacco)",
        "• E-cigarettes, vape pens, e-liquids, vaping accessories",
        "• Hookahs, shisha tobacco",
        "• Nicotine pouches, snus, chewing tobacco",
        "",
        "**PHARMACEUTICALS & MEDICAL PRODUCTS**",
        "• Prescription medications (antibiotics, painkillers, ADHD meds) - requires pharmacy license",
        "• Controlled substances (opioids, benzodiazepines, stimulants)",
        "• Medical devices (thermometers, blood pressure monitors, glucose meters) - requires medical device license",
        "• Dietary supplements making unverified health claims",
        "• Anabolic steroids, performance-enhancing drugs",
        "• Hormones, insulin, injectable medications",
        "",
        "**FINANCIAL SERVICES**",
        "• Investment advice, stock tips, trading signals - requires financial advisor license",
        "• Cryptocurrency exchanges, wallet services - requires money transmitter license",
        "• Debt collection, credit repair services - requires debt collector license",
        "• Insurance policies, annuities - requires insurance license",
        "• Tax preparation, accounting services - requires CPA license",
        "• Get-rich-quick schemes, pyramid schemes, Ponzi schemes",
        "",
        "**FOOD & AGRICULTURE**",
        "• Meat, poultry, dairy products - requires food handling permit and health inspection",
        "• Homemade foods without commercial kitchen certification",
        "• Raw milk, unpasteurized dairy products",
        "• Wild game meat without hunting permits",
        "• Endangered species products (ivory, rhino horn, tiger bones)",
      ],
      type: "callout-important",
    },
    {
      heading: "4. Adult Content & Services",
      content: [
        "**SEXUAL CONTENT**",
        "• Pornography, adult films, explicit sexual material",
        "• Sex toys, vibrators, dildos, BDSM equipment",
        "• Lingerie marketed as adult/sexual content (vs. regular clothing)",
        "• Webcam services, escort services, prostitution",
        "• OnlyFans content, Patreon adult creator content",
        "",
        "**DATING & PERSONAL SERVICES**",
        "• Mail-order bride services",
        "• Surrogacy services, egg donation",
        "• Baby-selling, adoption services (without licensed agency)",
      ],
      type: "text",
    },
    {
      heading: "5. Human Remains & Body Parts",
      content: [
        "• Human corpses, skeletons, skulls",
        "• Organs, blood, plasma, bodily fluids",
        "• Hair (for wigs/extensions) unless ethically sourced with documentation",
        "• Placenta, umbilical cords, amniotic fluid",
        "• Exceptions: Legally donated anatomical specimens for medical education, properly permitted archaeological artifacts",
      ],
      type: "text",
    },
    {
      heading: "6. Animals & Wildlife Products",
      content: [
        "**LIVE ANIMALS**",
        "• Live mammals, birds, reptiles, fish, insects (except through approved breeders with proper documentation)",
        "• Endangered species (CITES-listed animals)",
        "• Exotic pets (lions, tigers, bears, venomous snakes)",
        "• Dogs/cats from puppy mills or unlicensed breeders",
        "",
        "**WILDLIFE PRODUCTS**",
        "• Ivory, rhino horn, elephant products",
        "• Tiger bones, tiger skin, big cat products",
        "• Sea turtle shells, coral, marine mammal products",
        "• Fur from endangered species (leopard, cheetah, ocelot)",
        "• Bear bile, musk deer glands, traditional medicine ingredients from endangered species",
        "• Feathers from protected bird species (eagles, hawks, owls)",
      ],
      type: "text",
    },
    {
      heading: "7. Recalled & Unsafe Products",
      content: [
        "• Products subject to government safety recalls",
        "• Cribs, car seats, strollers that don't meet current safety standards",
        "• Helmets past their expiration date",
        "• Children's toys with lead paint, small detachable parts (choking hazards)",
        "• Electronics without proper safety certifications (UL, CE, FCC)",
        "• Laser pointers above 5mW (can cause eye damage)",
        "• Hoverboards with defective batteries (fire hazard)",
      ],
      type: "callout-important",
    },
    {
      heading: "8. Digital Goods & Services - Prohibited",
      content: [
        "**SOFTWARE & ACCOUNTS**",
        "• Cracked software, pirated games, torrent downloads",
        "• Streaming device jailbreaking services",
        "• Cable TV descramblers, satellite card hackers",
        "• Netflix, Spotify, Steam account sharing (violates terms of service)",
        "• Game cheats, aimbots, hacks, mod menus",
        "",
        "**DIGITAL COURSES & CONTENT**",
        "• Resold PLR (Private Label Rights) content without proper license",
        "• Courses teaching illegal activities (lock picking, drug manufacturing, hacking)",
        "• Fake diplomas, degrees, certificates",
        "",
        "**GAMBLING**",
        "• Online casino access, sports betting platforms - requires gambling license",
        "• Lottery tickets, raffle tickets across state/national borders",
        "• Gambling bots, lottery prediction software",
      ],
      type: "text",
    },
    {
      heading: "9. Government & Official Items",
      content: [
        "• Police badges, law enforcement uniforms, insignia",
        "• Military medals, decorations, uniforms (if impersonation intended)",
        "• Government IDs, passports, visas (counterfeit or real)",
        "• Stamps, postage meters (counterfeit)",
        "• Traffic tickets, court documents (forged)",
        "• Voting ballots, absentee ballot forms",
      ],
      type: "text",
    },
    {
      heading: "10. Surveillance & Espionage Equipment",
      content: [
        "• Wiretapping devices, phone bugs",
        "• Hidden cameras disguised as everyday objects (smoke detectors, clocks)",
        "• GPS trackers for stalking (without owner consent)",
        "• Cell phone jammers, signal blockers",
        "• Night vision goggles, thermal imaging (military-grade)",
        "• EMP devices, electromagnetic pulse generators",
      ],
      type: "text",
    },
    {
      heading: "11. Environmental Violations",
      content: [
        "• Ozone-depleting substances (CFCs, HCFCs)",
        "• Whale oil, seal pelts, products from hunted marine mammals",
        "• Conflict minerals (blood diamonds, coltan from war zones)",
        "• Rainforest hardwood (rosewood, mahogany) without sustainable certification",
        "• Shark fins, foie gras (banned in some jurisdictions)",
      ],
      type: "text",
    },
    {
      heading: "12. Other Prohibited Items",
      content: [
        "• Cemetery plots, burial rights (regulated real estate)",
        "• Timeshares, vacation club memberships (regulated securities)",
        "• Pyramid scheme participation, MLM inventory loading",
        "• SWAT team equipment, military surplus weapons",
        "• Pepper spray, mace, tasers (restricted in some jurisdictions)",
        "• Self-defense weapons (brass knuckles, sap gloves)",
        "• Graffiti spray paint (restricted for minors in some areas)",
        "• Spray paint markers over 15mm tip size (vandalism tool)",
        "• Glue, solvents marketed for inhalant abuse ('huffing')",
      ],
      type: "text",
    },
    {
      heading: "13. Gray Market & Restricted Distribution",
      content: [
        "Products legally restricted from online sale or requiring in-person verification:",
        "• Contact lenses, eyeglasses - requires valid prescription verification",
        "• Hearing aids - requires audiologist fitting",
        "• Mobility scooters, medical equipment - requires medical justification",
        "• Pesticides, herbicides - requires applicator license",
        "• Fireworks - consumer grade only where legal",
        "• Air guns, BB guns, pellet guns - age verification required",
        "• Paintball guns, airsoft guns - treated as firearms in some jurisdictions",
      ],
      type: "callout-important",
    },
    {
      heading: "14. Enforcement & Reporting",
      content: [
        "**Detection Methods:**",
        "We use automated tools, image recognition, keyword scanning, and manual review to detect prohibited items. Our AI systems scan product titles, descriptions, images, and customer reports.",
        "",
        "**Consequences:**",
        "• First violation: Product removal + written warning",
        "• Second violation: 7-day store suspension + mandatory policy re-education",
        "• Third violation: Permanent store termination + forfeiture of outstanding payouts",
        "• Immediate termination: Illegal items, counterfeits, dangerous products",
        "",
        "**How to Report:**",
        "If you see a violation, report it immediately to support@vayva.ng with subject line 'Prohibited Items Report'. Include:",
        "• Store URL or merchant name",
        "• Product link or screenshot",
        "• Which prohibited category it violates",
        "• Any additional evidence (chat logs, customer complaints)",
        "",
        "All reports are kept confidential. We investigate within 24 hours and take appropriate action.",
      ],
      type: "text",
    },
    {
      heading: "15. Updates to This Policy",
      content: [
        "We update this policy regularly to reflect changes in law, emerging risks, and new product categories. Material changes are communicated via email 7 days before taking effect.",
        "Merchants are responsible for staying informed about prohibited items. Ignorance of this policy is not a defense against violations.",
        "Last updated: March 18, 2026. Next review: June 2026.",
      ],
      type: "text",
    },
  ],
};
