/**
 * SUBPROCESSOR LIST
 * 
 * Required by: GDPR Article 28(3), UK GDPR Article 28(3)
 * Public transparency document listing all third-party data processors
 */

import { LegalDocument } from "../types";

export const subprocessors: LegalDocument = {
  slug: "subprocessors",
  title: "Authorized Subprocessors",
  lastUpdated: "March 19, 2026",
  version: "1.0",
  summary:
    "Complete list of third-party service providers (subprocessors) authorized to process personal data on behalf of Vayva merchants.",
  sections: [
    {
      heading: "Overview",
      content: [
        "Vayva engages specialized third-party service providers to deliver our platform services. Each subprocessor has been carefully selected and contracted to provide adequate guarantees of appropriate technical and organizational security measures in compliance with GDPR Article 28, UK GDPR Article 28, and NDPR requirements.",
        "",
        "Your Rights:",
        "• You have the right to object to new subprocessors within 30 days of notice",
        "• We will notify you via email before adding new subprocessors",
        "• If you object and we cannot find an alternative, you may terminate your account",
        "• All subprocessors are bound by Data Processing Agreements (DPAs) with Standard Contractual Clauses where required",
      ],
      type: "callout-important",
    },
    {
      heading: "Payment Processing",
      content: [
        "Paystack Technologies Limited",
        "• Purpose: Payment card processing, bank transfers, wallet transactions",
        "• Data Processed: Card numbers (encrypted), bank account details, transaction amounts, customer names",
        "• Location: Nigeria (primary), United Kingdom (backup processing)",
        "• Safeguards: PCI DSS Level 1 certified, NDPR compliant, ISO 27001 certified",
        "• Website: https://paystack.com/terms/",
        "• DPA Status: Signed with SCCs",
        "",
        "Why Paystack:",
        "Paystack enables secure payment processing without Vayva ever handling raw card data. All payment information is transmitted directly to Paystack's PCI DSS Level 1 infrastructure using TLS 1.3 encryption. Vayva only receives confirmation of successful payments and transaction metadata (amount, timestamp, order ID).",
      ],
      type: "definitions",
    },
    {
      heading: "Identity Verification & KYC",
      content: [
        "Manual Verification by Vayva Compliance Team",
        "• Purpose: NIN verification, BVN verification, CAC document review",
        "• Data Processed: NIN numbers, BVN numbers, government IDs, business registration documents",
        "• Location: Nigeria (Lagos office)",
        "• Safeguards: Encrypted storage (AES-256), access controls, audit logs, NDPR compliance",
        "• Process: Internal compliance team performs verification via official government portals",
        "",
        "Government Verification Portals:",
        "• NIMC (National Identity Management Commission): NIN verification via official API",
        "• CBN (Central Bank of Nigeria): BVN verification via approved banking partners",
        "• CAC (Corporate Affairs Commission): Business verification via CAC public registry",
        "",
        "Note: Vayva does not store full BVN numbers. We only receive pass/fail confirmation from verification checks.",
      ],
      type: "text",
    },
    {
      heading: "Cloud Infrastructure & Hosting",
      content: [
        "Amazon Web Services (AWS)",
        "• Purpose: Cloud hosting, database storage, file storage, backup",
        "• Data Processed: All platform data (user accounts, products, orders, analytics)",
        "• Location: AWS regions vary (primary: af-south-1 Cape Town, fallback: eu-west-1 Ireland)",
        "• Safeguards: SOC 2 Type II, ISO 27001, ISO 27017 (cloud security), ISO 27018 (cloud privacy), GDPR-compliant Data Processing Addendum",
        "• Website: https://aws.amazon.com/compliance/",
        "• DPA Status: AWS Data Processing Addendum accepted (includes SCCs)",
        "",
        "Cloudflare Inc.",
        "• Purpose: CDN (Content Delivery Network), DDoS protection, DNS management",
        "• Data Processed: IP addresses, browser fingerprints, request headers",
        "• Location: Global network (data centers in 120+ countries)",
        "• **Safeguards**: SOC 2 Type II, ISO 27001, GDPR-compliant Data Processing Agreement",
        "• **Website**: https://www.cloudflare.com/trust-hub/",
        "• **DPA Status**: Signed",
      ],
      type: "definitions",
    },
    {
      heading: "Analytics & Monitoring",
      content: [
        "**Google Ireland Limited (Google Analytics)**",
        "• **Purpose**: Website usage analytics, user behavior tracking, conversion measurement",
        "• **Data Processed**: IP addresses (anonymized), device information, page views, session duration, bounce rates",
        "• **Location**: EU servers (with Google US access under Data Privacy Framework)",
        "• **Safeguards**: IP anonymization enabled, data retention limited to 26 months, GDPR-compliant configuration",
        "• **Opt-Out**: Browser plugin available at https://tools.google.com/dlpage/gaoptout",
        "• **Website**: https://policies.google.com/privacy",
        "",
        "**Hotjar Ltd.**",
        "• **Purpose**: Heatmaps, session recordings, user feedback surveys",
        "• **Data Processed**: Mouse movements, clicks, scroll behavior, anonymized IP addresses",
        "• **Location**: Malta (EU), with global CDN",
        "• **Safeguards**: GDPR compliant, data anonymization, IP masking, do-not-track respect",
        "• **Opt-Out**: https://www.hotjar.com/legal/compliance/opt-out",
        "• **Website**: https://www.hotjar.com/legal/policies/privacy-policy/",
        "",
        "**Note**: Both analytics tools require user consent via cookie banner before activation.",
      ],
      type: "text",
    },
    {
      heading: "Marketing & Communications",
      content: [
        "**Meta Platforms Ireland Limited (Facebook Pixel)**",
        "• **Purpose**: Ad performance tracking, conversion measurement, audience building",
        "• **Data Processed**: Browser events, purchase data, page views (hashed and anonymized)",
        "• **Location**: EU/US (under EU-US Data Privacy Framework)",
        "• **Safeguards**: Advanced Matching (hashing), aggregated reporting only",
        "• **Opt-Out**: https://www.facebook.com/settings?tab=ads",
        "• **Website**: https://www.facebook.com/about/privacy/",
        "",
        "**Google Ireland Limited (Google Ads)**",
        "• **Purpose**: Conversion tracking, remarketing, ad performance measurement",
        "• **Data Processed**: Click IDs, conversion events, device information",
        "• **Location**: EU/US (under EU-US Data Privacy Framework)",
        "• **Safeguards**: Encrypted transmission, aggregated reporting",
        "• **Opt-Out**: https://support.google.com/ads/answer/2662922",
        "",
        "**Microsoft Corporation (TikTok Pixel, LinkedIn Insight Tag)**",
        "• **Purpose**: Ad conversion tracking, professional audience targeting",
        "• **Data Processed**: Conversion events, job titles (LinkedIn), hashed emails",
        "• **Location**: EU/US (under respective adequacy decisions)",
        "• **Safeguards**: Hashing, pseudonymization, aggregated analytics",
        "• **Opt-Out**: Platform-specific settings",
      ],
      type: "text",
    },
    {
      heading: "Customer Support & Communications",
      content: [
        "**Email Delivery (Self-Hosted)**",
        "• **Purpose**: Transactional emails (order confirmations, password resets, notifications)",
        "• **Data Processed**: Email addresses, names, order details, notification content",
        "• **Location**: Hosted on same infrastructure as main platform (AWS)",
        "• **Safeguards**: TLS encryption in transit, encrypted storage, access controls",
        "• **Provider**: Self-hosted mail server on vayva.ng domain",
        "",
        "**WhatsApp Business API (Future)**",
        "• **Purpose**: Order updates, support communications (only if merchant opts in)",
        "• **Data Processed**: Phone numbers, message content, delivery status",
        "• **Location**: Meta infrastructure (global)",
        "• **Status**: Not yet implemented - will update this list before activation",
        "• **Safeguards**: Will implement end-to-end encryption, opt-in consent only",
      ],
      type: "text",
    },
    {
      heading: "Security & Fraud Prevention",
      content: [
        "**Internal Security Systems (Self-Built)**",
        "• **Purpose**: Fraud detection, intrusion detection, access monitoring",
        "• **Data Processed**: Login attempts, IP addresses, transaction patterns, user behavior",
        "• **Location**: Hosted on Vayva infrastructure (AWS)",
        "• **Safeguards**: Real-time monitoring, automated alerts, manual review for high-risk events",
        "• **Technology**: Custom-built fraud detection algorithms, rate limiting, anomaly detection",
        "",
        "**Note**: Vayva does not currently use third-party fraud prevention services. All security monitoring is performed in-house by our security team.",
      ],
      type: "text",
    },
    {
      heading: "Development & Operations",
      content: [
        "**GitHub Inc.**",
        "• **Purpose**: Source code hosting, version control, CI/CD pipelines",
        "• **Data Processed**: Developer email addresses, commit history, code repositories",
        "• **Location**: US (with global CDN)",
        "• **Safeguards**: SOC 2 Type II, ISO 27001, two-factor authentication mandatory",
        "• **Website**: https://docs.github.com/en/site-policy/privacy-policies",
        "",
        "**Vercel Inc. (Optional - if used for deployments)**",
        "• **Purpose**: Frontend deployment, preview environments, edge functions",
        "• **Data Processed**: Build logs, deployment metadata, edge function requests",
        "• **Location**: US (with global edge network)",
        "• **Safeguards**: SOC 2 Type II, GDPR-compliant DPA",
        "• **Status**: Currently evaluating - not yet in production use",
      ],
      type: "text",
    },
    {
      heading: "Data Retention & Deletion",
      content: [
        "**How Long Subprocessors Keep Data:**",
        "• **Paystack**: 7 years after last transaction (Nigerian financial records law)",
        "• **AWS**: Until deletion requested + 90-day backup retention",
        "• **Google Analytics**: 26 months from collection (auto-deletion configured)",
        "• **Cloudflare**: 30 days for logs, immediate for cached content",
        "• **Hotjar**: 365 days from collection, then anonymized",
        "",
        "**Your Right to Deletion:**",
        "You can request deletion of data held by subprocessors by emailing support@vayva.ng. We will forward deletion requests to relevant subprocessors within 7 days. Note that some subprocessors (like Paystack) are legally required to retain certain data for regulatory compliance.",
      ],
      type: "callout-important",
    },
    {
      heading: "International Data Transfers",
      content: [
        "**Transfer Mechanisms:**",
        "• **EU → US**: EU-US Data Privacy Framework (adequacy decision July 2023)",
        "• **EU → UK**: UK adequacy decision (expires June 2025)",
        "• **EU → Nigeria**: Standard Contractual Clauses (SCCs) with AWS",
        "• **UK → Non-UK**: International Data Transfer Agreement (IDTA) where required",
        "",
        "**Subprocessors Outside Your Region:**",
        "If you are located in Nigeria, your data may be transferred to:",
        "• European Economic Area (for cloud hosting, analytics)",
        "• United Kingdom (for marketing tools)",
        "• United States (for development tools, some marketing platforms)",
        "• South Africa (primary AWS hosting region)",
        "",
        "All transfers are protected by appropriate safeguards (SCCs, IDTAs, or adequacy decisions).",
      ],
      type: "text",
    },
    {
      heading: "Objecting to Subprocessors",
      content: [
        "**How to Object:**",
        "1. Review new subprocessor notice (sent via email)",
        "2. Email support@vayva.ng with subject 'Subprocessor Objection'",
        "3. Include which subprocessor you object to and why",
        "4. We will respond within 7 days with options",
        "",
        "**What Happens Next:**",
        "• If feasible, we will find an alternative subprocessor that meets your concerns",
        "• If no alternative exists and concern is legitimate, we will not engage the subprocessor",
        "• If engagement is necessary and you maintain objection, you may terminate your account",
        "",
        "**Updates to This List:**",
        "We update this page regularly. Material changes are notified via email 30 days before new subprocessor becomes active. Check back periodically or subscribe to update notifications.",
      ],
      type: "text",
    },
    {
      heading: "Contact & Questions",
      content: [
        "**For questions about subprocessors:**",
        "Email: support@vayva.ng with subject 'Subprocessor Inquiry'",
        "Response time: Within 5 business days",
        "",
        "**For privacy concerns:**",
        "Email: support@vayva.ng with subject 'Privacy Rights Request'",
        "Response time: Within 30 days (GDPR) / 7 days (NDPR urgent)",
        "",
        "**Last Updated:** March 18, 2026",
        "**Next Review:** June 2026 (quarterly subprocessor audit)",
      ],
      type: "text",
    },
  ],
};
