import type { LegalDocument } from "../types";

export const termsOfService: LegalDocument = {
  slug: "terms",
  title: "Terms of Service",
  lastUpdated: "March 18, 2026",
  version: "1.0",
  summary:
    "These comprehensive terms govern use of the Vayva platform, including merchant tools, storefronts, and related services. Please read carefully as they affect your legal rights.",
  sections: [
    {
      heading: "1. Introduction",
      content: [
        "These Terms of Service govern your access to and use of the Vayva platform and related services. By using the Service you agree to these Terms.",
      ],
      type: "text",
    },
    {
      heading: "2. Eligibility",
      content: [
        "You must be at least 18 years old and have legal capacity to operate a business. You must provide accurate registration information and keep it updated.",
        "**Account Security:**",
        "• You must create strong passwords with at least 12 characters including uppercase, lowercase, numbers, and symbols",
        "• You may not share your account credentials or allow others to access your account except authorized team members you invite",
        "• You must notify us immediately of unauthorized access at support@vayva.ng",
        "• You are responsible for all activities that occur under your account",
        "• We reserve the right to disable accounts we believe have been compromised",
      ],
    },
    {
      heading: "3. Service Overview",
      content: [
        "Vayva provides software tools that help merchants organize sales, payments, inventory, delivery, and customer communications. Vayva does not buy, sell, or broker goods or services. Transactions are between you and your customers.",
      ],
    },
    {
      heading: "4. Verification and Compliance",
      content: [
        "We may require identity and business verification to comply with legal and risk controls. Verification can include NIN, BVN, and CAC checks. We may use Paystack and/or manual review through our Compliance Team. You agree to provide accurate documents and keep verification information current.",
      ],
    },
    {
      heading: "5. Merchant Responsibilities",
      content: [
        "You are responsible for the goods or services you offer, pricing, fulfillment, customer support, and compliance with applicable laws. You are responsible for ensuring that all data you enter is accurate and that you have the right to use it.",
      ],
    },
    {
      heading: "6. Prohibited Use",
      content: [
        "You may not use the Service for illegal or fraudulent activity, prohibited items, misuse of customer data, or attempts to bypass security or access controls. We may suspend or terminate accounts for violations.",
      ],
    },
    {
      heading: "7. Payments and Fees",
      content: [
        "Paid plans and fees are billed in advance unless otherwise stated. You are responsible for applicable taxes. Payment processing may involve third party providers and their terms apply to your use of those services.",
      ],
    },
    {
      heading: "8. Data and Content",
      content: [
        "You own your business data. You grant Vayva a limited, nonexclusive license to process that data to provide the Service, improve functionality, and comply with legal obligations. You are responsible for any content you upload or send through the Service.",
      ],
    },
    {
      heading: "9. Suspension and Termination",
      content: [
        "We may suspend or terminate access if you violate these Terms, fail to pay fees, or create legal or security risk. You may close your account at any time.",
        "**Termination Process:**",
        "• **Voluntary Termination**: Email support@vayva.ng with subject 'Account Closure'. Effective immediately or at specified date.",
        "• **Termination for Cause**: We provide 30 days notice for curable breaches, immediate termination for serious violations (fraud, illegal activity, security threats).",
        "• **Effect of Termination**: Access to platform ends, outstanding fees become immediately due, data export available for 30 days post-termination.",
        "",
        "**Data Export and Deletion:**",
        "• You can export your data (products, customers, orders) via dashboard before termination",
        "• We provide data in CSV/JSON format within 7 days of request",
        "• After 30 days post-termination, data is securely deleted unless legally required to retain",
        "• Backup copies retained for disaster recovery are deleted within 90 days",
        "• Deletion is irreversible - ensure you have exported needed data",
      ],
    },
    {
      heading: "10. Data and Content",
      content: [
        "You own your business data. You grant Vayva a limited, nonexclusive, royalty-free, worldwide license to use, reproduce, modify, adapt, publish, translate, and display your business data solely to provide the Service, improve functionality, and comply with legal obligations.",
        "This license allows us to:",
        "• Show your products in storefronts and marketplaces",
        "• Process transactions on your behalf",
        "• Perform analytics to improve our services",
        "• Display testimonials and case studies (with your consent)",
        "• Backup and restore your data for business continuity",
        "You retain all ownership rights in your trademarks, logos, product images, descriptions, and other proprietary content. This license does not include the right to sell, license, or monetize your data to third parties.",
        "You are responsible for any content you upload or send through the Service and warrant that you have all necessary rights and permissions.",
      ],
    },
    {
      heading: "11. Disclaimers",
      content: [
        "The Service is provided on an as is and as available basis. We do not guarantee uninterrupted availability or error free operation.",
      ],
    },
    {
      heading: "11. Limitation of Liability",
      content: [
        "To the maximum extent permitted by law, Vayva is not liable for indirect, incidental, or consequential damages, loss of profits, or loss of business opportunities. Our total liability is limited to the fees paid by you in the twelve months before the event that gave rise to the claim.",
      ],
    },
    {
      heading: "12. Indemnity",
      content: [
        "You agree to indemnify and hold Vayva harmless from claims arising from your use of the Service, your content, or your violation of law or third party rights.",
      ],
    },
    {
      heading: "13. Changes",
      content: [
        "We may update these Terms. Continued use after notice means you accept the updated Terms.",
        "**Notification of Changes:**",
        "• **Material Changes**: 30 days advance notice via email and in-app notification",
        "• **Minor Changes** (typos, clarifications): Immediate effect, posted on website",
        "• **Emergency Changes** (security, legal compliance): Immediate effect with prompt notification",
        "",
        "**Your Rights:**",
        "• Review changes at vayva.ng/legal/terms/changelog",
        "• Object to material changes by closing account before effective date",
        "• Continued use after effective date constitutes acceptance",
        "• If you disagree with changes, your sole remedy is to terminate your account",
      ],
    },
    {
      heading: "14. Force Majeure",
      content: [
        "Vayva shall not be liable for delays, interruptions, or failures in performance resulting from causes beyond our reasonable control, including but not limited to:",
        "• Natural disasters (earthquakes, floods, hurricanes, pandemics)",
        "• Acts of war, terrorism, civil unrest, government actions",
        "• Labor disputes, strikes, shortages",
        "• Internet infrastructure failures, ISP outages, DDoS attacks",
        "• Power outages, telecommunications failures",
        "• Cloud provider outages (AWS, Azure, Google Cloud)",
        "",
        "During force majeure events, we will:",
        "• Use commercially reasonable efforts to mitigate impact",
        "• Provide status updates via status.vayva.ng",
        "• Resume performance as soon as practicable",
        "• Extend subscription terms by duration of service interruption",
      ],
      type: "text",
    },
    {
      heading: "15. Business Continuity",
      content: [
        "**If Vayva Discontinues Operations:**",
        "• We will provide at least 90 days advance notice via email",
        "• You will have full access to export all your data during this period",
        "• We will assist with migration to alternative platforms",
        "• Prepaid subscription fees will be refunded pro-rata",
        "• Customer data will be returned or securely destroyed per your instructions",
        "",
        "**Escrow Arrangements:**",
        "For enterprise customers concerned about business continuity, we offer source code escrow agreements for an additional fee. Contact sales@vayva.ng for details.",
      ],
      type: "callout-important",
    },
    {
      heading: "16. API Usage and Rate Limits",
      content: [
        "Vayva provides APIs for integration with third-party applications. API usage is governed by these additional terms:",
        "",
        "**Rate Limits:**",
        "• Starter Plan: 100 requests per minute, 10,000 requests per day",
        "• Pro Plan: 500 requests per minute, 100,000 requests per day",
        "• Enterprise Plan: Custom limits based on needs",
        "",
        "**API Restrictions:**",
        "• You may not attempt to bypass rate limits or throttling mechanisms",
        "• You may not use APIs to create competing services",
        "• You may not scrape, harvest, or aggregate data for resale",
        "• You must comply with API terms of service and developer policies",
        "• Abuse may result in API access suspension or termination",
        "",
        "**API Changes:**",
        "We may deprecate API endpoints with 90 days notice. Critical security updates may be applied immediately.",
      ],
      type: "text",
    },
    {
      heading: "17. Third-Party Services Integration",
      content: [
        "Vayva integrates with third-party services (Paystack for payments, logistics providers for delivery, etc.). These integrations are subject to the third party's terms and privacy policies.",
        "",
        "**Payment Processing:**",
        "• Payments processed by Paystack (PCI DSS Level 1 certified)",
        "• Paystack's Terms of Service apply to payment processing",
        "• Vayva does not store or transmit full card numbers",
        "• Chargebacks and disputes handled per Paystack policies",
        "",
        "**Delivery & Logistics:**",
        "• Delivery partners (GIG Logistics, DHL, FedEx, etc.) have their own terms",
        "• Vayva is not liable for delivery delays, lost packages, or damage in transit",
        "• Shipping insurance available for high-value items",
        "",
        "**Limitation of Liability:**",
        "Vayva acts as intermediary for third-party services. We do not guarantee third-party performance and are not liable for their actions or omissions. Your recourse is directly with the third-party provider.",
      ],
      type: "callout-important",
    },
    {
      heading: "14. Governing Law and Dispute Resolution",
      content: [
        "These Terms are governed by the laws of the Federal Republic of Nigeria. However, if you are a consumer located in the European Economic Area (EEA), United Kingdom, or other jurisdictions with mandatory consumer protection laws, those laws shall apply to the extent required.",
        "For commercial users: Any disputes shall be resolved through good faith negotiations. If unresolved within 30 days, disputes may be brought in the courts of Nigeria or your jurisdiction of business establishment, at the option of either party.",
        "For consumers in EEA/UK: You may bring claims in your country of residence. Nigerian law and courts apply only if you explicitly agree after being informed of this right.",
        "",
        "**Alternative Dispute Resolution:**",
        "Before pursuing litigation, parties agree to attempt mediation via:",
        "• Lagos Court of Arbitration (LCA) for Nigerian disputes",
        "• CEDR (Centre for Effective Dispute Resolution) for UK disputes",
        "• Mediation costs split equally unless settlement reached",
        "",
        "**Class Action Waiver:**",
        "TO THE EXTENT PERMITTED BY LAW, BOTH PARTIES AGREE TO RESOLVE DISPUTES ON AN INDIVIDUAL BASIS AND WAIVE ANY RIGHT TO PARTICIPATE IN CLASS ACTIONS OR COLLECTIVE ARBITRATIONS.",
      ],
    },
    {
      heading: "18. Contact",
      content: ["For questions about these Terms, contact us at: support@vayva.ng"],
    },
  ],
};
