export const FOOD_TEMPLATES = {
  "vayva-chopnow": {
    templateId: "vayva-chopnow",
    slug: "chopnow-demo",
    displayName: "ChopNow",
    category: "Food",
    industry: "food",
    businessModel: "Food",
    primaryUseCase: "Food Delivery / Restaurants",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Fast menu ordering for restaurants.",
      bullets: [
        "Modifier groups (sides, toppings)",
        "Delivery vs Pickup toggle",
        "Visual menu categories",
      ],
      bestFor: ["Restaurants", "Fast Food", "Cloud Kitchens"],
      keyModules: [
        "Kitchen Display System",
        "Menu Modifiers",
        "Delivery Zones",
      ],
    },
    routes: ["/"],
    layoutKey: "QuickBitesFood",
    onboardingProfile: {
      prefill: {
        industryCategory: "food",
        deliveryEnabled: true,
        paymentsEnabled: true,
      },
      requireSteps: ["logistics", "finance"],
    },
  },
  "slice-life-pizza": {
    templateId: "slice-life-pizza",
    slug: "slice-life",
    displayName: "Slice Life Pizza",
    category: "Food",
    industry: "food",
    businessModel: "Food",
    primaryUseCase: "Pizzerias",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    demoStoreUrl: "/demos/slice-life",
    compare: {
      headline: "Artisanal pizza experience.",
      bullets: [
        "Visual menu with modifiers",
        "Delivery zone checker",
        "Combo builder",
      ],
      bestFor: ["Pizzerias", "Italian Restaurants"],
      keyModules: ["Menu Builder", "Modifiers", "Delivery"],
    },
    routes: ["/"],
    layoutKey: "SliceLifePizza",
    onboardingProfile: {
      prefill: {
        industryCategory: "food",
        deliveryEnabled: true,
        paymentsEnabled: true,
      },
      requireSteps: ["logistics", "finance"],
    },
  },
  "vayva-coffee-house": {
    templateId: "vayva-coffee-house",
    slug: "coffee-demo",
    displayName: "Coffee House",
    category: "Food",
    industry: "food",
    businessModel: "Food",
    primaryUseCase: "Cafe / Coffee Shop",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Order ahead for morning brew.",
      bullets: ["Custom drink builder", "Pickup scheduling", "Loyalty points"],
      bestFor: ["Cafes", "Roasters"],
      keyModules: ["Modifiers", "Loyalty"],
    },
    routes: ["/"],
    layoutKey: "QuickBitesFood",
    onboardingProfile: { prefill: { industryCategory: "food" } },
  },
  "vayva-burger-joint": {
    templateId: "vayva-burger-joint",
    slug: "burger-demo",
    displayName: "Burger Joint",
    category: "Food",
    industry: "food",
    businessModel: "Food",
    primaryUseCase: "Fast Food",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Juicy burgers, fast delivery.",
      bullets: ["Combo deals", "Topping selectors", "Fast checkout"],
      bestFor: ["Burger Shops", "Food Trucks"],
      keyModules: ["Combos", "Delivery"],
    },
    routes: ["/"],
    layoutKey: "QuickBitesFood",
    onboardingProfile: { prefill: { industryCategory: "food" } },
  },
  "vayva-sushi-bar": {
    templateId: "vayva-sushi-bar",
    slug: "sushi-demo",
    displayName: "Sushi Bar",
    category: "Food",
    industry: "food",
    businessModel: "Food",
    primaryUseCase: "Asian Cuisine",
    requiredPlan: "free",
    defaultTheme: "dark",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Elegant dining experience.",
      bullets: ["Omakase menu", "Reservation booking", "Visual gallery"],
      bestFor: ["Sushi", "Fine Dining"],
      keyModules: ["Reservations", "Menu Gallery"],
    },
    routes: ["/"],
    layoutKey: "StandardFoodHome",
    onboardingProfile: { prefill: { industryCategory: "food" } },
  },
  "vayva-bakery": {
    templateId: "vayva-bakery",
    slug: "bakery-demo",
    displayName: "Sweet Bakery",
    category: "Food",
    industry: "food",
    businessModel: "Food",
    primaryUseCase: "Bakery / Sweets",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Fresh pastries daily.",
      bullets: ["Cake customization", "Pre-order for events", "Gift boxes"],
      bestFor: ["Bakeries", "Patisseries"],
      keyModules: ["Custom Orders", "Scheduling"],
    },
    routes: ["/"],
    layoutKey: "StandardFoodHome",
    onboardingProfile: { prefill: { industryCategory: "food" } },
  },
};
