export const RETAIL_TEMPLATES = {
  "vayva-standard": {
    templateId: "vayva-standard",
    slug: "demo",
    displayName: "Standard Retail",
    category: "Retail",
    industry: "retail",
    businessModel: "Retail",
    primaryUseCase: "General Physical Goods",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "The essential store for physical products.",
      bullets: [
        "Classic hero banner with CTA",
        "Clean collection grid layout",
        "Simple product details page",
      ],
      bestFor: ["Clothing boutiques", "General merchandise", "Pop-up shops"],
      keyModules: ["Product Catalog", "Cart & Checkout", "Order Management"],
    },
    routes: ["/", "/collections/*", "/products/:slug"],
    layoutKey: "StandardRetailHome",
    onboardingProfile: {
      prefill: {
        industryCategory: "retail",
        deliveryEnabled: true,
        paymentsEnabled: true,
      },
      requireSteps: ["finance"],
    },
  },
  "vayva-aa-fashion": {
    templateId: "vayva-aa-fashion",
    slug: "aa-fashion-demo",
    displayName: "A&A Fashion",
    category: "Retail",
    industry: "fashion",
    businessModel: "Retail",
    primaryUseCase: "Fashion / Apparel",
    requiredPlan: "free",
    defaultTheme: "dark",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Bold, visual-first fashion retail.",
      bullets: [
        "Full-width imagery focused",
        "Lookbook style collections",
        "Size guide modal integration",
      ],
      bestFor: ["Fashion brands", "Streetwear", "Luxury apparel"],
      keyModules: ["Visual Merchandising", "Size Variants", "Instagram Feed"],
    },
    routes: ["/", "/collections/*", "/products/:slug"],
    layoutKey: "AAFashionHome",
    componentProps: {
      heroText: "DARK\nMATTER",
      heroSubtext: "Season 04 / 24",
    },
    onboardingProfile: {
      prefill: {
        industryCategory: "fashion",
        deliveryEnabled: true,
        paymentsEnabled: true,
      },
      requireSteps: ["finance"],
    },
  },
  "vayva-gizmo-tech": {
    templateId: "vayva-gizmo-tech",
    slug: "gizmo-demo",
    displayName: "Gizmo Tech",
    category: "Retail",
    industry: "electronics",
    businessModel: "Retail",
    primaryUseCase: "Electronics",
    requiredPlan: "free",
    defaultTheme: "dark",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "High-spec showcase for electronics.",
      bullets: [
        "Spec comparison tables",
        "Dark mode technical aesthetic",
        "Feature highlight grids",
      ],
      bestFor: ["Gadget stores", "Computer shops", "Audio equipment"],
      keyModules: ["Tech Specs", "Product Comparison", "Warranty Info"],
    },
    routes: ["/", "/collections/*", "/products/:slug"],
    layoutKey: "GizmoTechHome",
    onboardingProfile: {
      prefill: {
        industryCategory: "electronics",
        deliveryEnabled: true,
        paymentsEnabled: true,
      },
      requireSteps: ["finance"],
    },
  },
  "vayva-bloome-home": {
    templateId: "vayva-bloome-home",
    slug: "bloome-demo",
    displayName: "Bloome & Home",
    category: "Retail",
    industry: "beauty",
    businessModel: "Retail",
    primaryUseCase: "Home & Lifestyle",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Serene design for lifestyle and beauty.",
      bullets: [
        "Editorial style storytelling",
        "Soft typography and palettes",
        "Ritual/Routine builder layouts",
      ],
      bestFor: ["Home decor", "Skincare/Beauty", "Wellness brands"],
      keyModules: [
        "Subscription Support",
        "Bundle Builder",
        "Blog Integration",
      ],
    },
    routes: ["/", "/collections/*", "/products/:slug"],
    layoutKey: "BloomeHome",
    onboardingProfile: {
      prefill: {
        industryCategory: "beauty",
        deliveryEnabled: true,
        paymentsEnabled: true,
      },
      requireSteps: ["finance"],
    },
  },
  "vayva-oneproduct": {
    templateId: "vayva-oneproduct",
    slug: "oneproduct-demo",
    displayName: "OneProduct Pro",
    category: "Retail",
    industry: "retail",
    businessModel: "Single Product",
    primaryUseCase: "Funnel / Landing Page",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "High-conversion single product funnel.",
      bullets: [
        "Long-form persuasion layout",
        "Sticky 'Buy Now' mobile CTA",
        "integrated upsell flows",
      ],
      bestFor: ["Dropshippers", "Inventors", "Flash Sales"],
      keyModules: ["Funnel Builder", "Upsells", "Reviews/Social Proof"],
    },
    routes: ["/"],
    layoutKey: "OneProductHome",
    onboardingProfile: {
      prefill: {
        industryCategory: "retail",
        deliveryEnabled: true,
        paymentsEnabled: true,
      },
      requireSteps: ["finance"],
    },
  },
  "vayva-sneaker-drop": {
    templateId: "vayva-sneaker-drop",
    slug: "sneaker-demo",
    displayName: "Sneaker Drop",
    category: "Retail",
    industry: "fashion",
    businessModel: "Retail",
    primaryUseCase: "Streetwear / Shoes",
    requiredPlan: "free",
    defaultTheme: "dark",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Hype drops and limited editions.",
      bullets: ["Countdown timer", "Raffle system", "High-res gallery"],
      bestFor: ["Sneakerheads", "Streetwear Brands"],
      keyModules: ["Drop Timer", "Waitlist", "Stock Limits"],
    },
    routes: ["/"],
    layoutKey: "AAFashionHome",
    componentProps: {
      heroText: "SNEAKER\nDROP",
      heroSubtext: "Limited Release",
      showTimer: true,
      timerDate: "2025-12-31T00:00:00Z",
    },
    onboardingProfile: { prefill: { industryCategory: "fashion" } },
  },
  "vayva-kids-world": {
    templateId: "vayva-kids-world",
    slug: "kids-demo",
    displayName: "Kids World",
    category: "Retail",
    industry: "retail",
    businessModel: "Retail",
    primaryUseCase: "Toys / Clothing",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Fun and playful store for kids.",
      bullets: ["Bright colors", "Age filters", "Gift bundles"],
      bestFor: ["Toy Stores", "Baby Clothes"],
      keyModules: ["Gift Registry", "Age Filter"],
    },
    routes: ["/"],
    layoutKey: "StandardRetailHome",
    onboardingProfile: { prefill: { industryCategory: "retail" } },
  },
  "vayva-pet-palace": {
    templateId: "vayva-pet-palace",
    slug: "pet-demo",
    displayName: "Pet Palace",
    category: "Retail",
    industry: "retail",
    businessModel: "Retail",
    primaryUseCase: "Pet Supplies",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Where pets are royalty.",
      bullets: ["Subscription treats", "Breed guide", "Vet advice blog"],
      bestFor: ["Pet Shops", "Groomers"],
      keyModules: ["Subscriptions", "Blog"],
    },
    routes: ["/"],
    layoutKey: "StandardRetailHome",
    onboardingProfile: { prefill: { industryCategory: "retail" } },
  },
  "vayva-beauty-box": {
    templateId: "vayva-beauty-box",
    slug: "beauty-demo",
    displayName: "Beauty Box",
    category: "Retail",
    industry: "beauty",
    businessModel: "Retail",
    primaryUseCase: "Subscription Box",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Curated beauty delivered monthly.",
      bullets: ["Quiz funnel", "Monthly themes", "Unboxing experience"],
      bestFor: ["Subscription Boxes", "Cosmetics"],
      keyModules: ["Quiz", "Recurring Billing"],
    },
    routes: ["/"],
    layoutKey: "BloomeHome",
    onboardingProfile: { prefill: { industryCategory: "beauty" } },
  },
  "vayva-active-gear": {
    templateId: "vayva-active-gear",
    slug: "active-demo",
    displayName: "Active Gear",
    category: "Retail",
    industry: "retail",
    businessModel: "Retail",
    primaryUseCase: "Sports / Outdoors",
    requiredPlan: "free",
    defaultTheme: "dark",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Performance gear for athletes.",
      bullets: ["Tech specs", "Activity filter", "Team orders"],
      bestFor: ["Sports Shops", "Outdoor Gear"],
      keyModules: ["Filters", "Bulk Orders"],
    },
    routes: ["/"],
    layoutKey: "GizmoTechHome",
    onboardingProfile: { prefill: { industryCategory: "retail" } },
  },
};
