export const SERVICE_TEMPLATES = {
  "vayva-bookly-pro": {
    templateId: "vayva-bookly-pro",
    slug: "bookly-demo",
    displayName: "Bookly Pro",
    category: "Service",
    industry: "services",
    businessModel: "Service",
    primaryUseCase: "Appointments / Bookings",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Professional booking system for experts.",
      bullets: [
        "Real-time calendar availability",
        "Service menu with duration",
        "Deposit requirement handling",
      ],
      bestFor: ["Consultants", "Salons & Spas", "Clinics"],
      keyModules: ["Appointment Scheduling", "Staff Management", "Deposits"],
    },
    routes: ["/", "/book/:serviceId"],
    layoutKey: "StandardServiceHome",
    onboardingProfile: {
      prefill: {
        industryCategory: "services",
        deliveryEnabled: false,
        paymentsEnabled: true,
      },
      skipSteps: ["logistics"],
      requireSteps: ["finance"],
    },
  },
  "vayva-eduflow": {
    templateId: "vayva-eduflow",
    slug: "eduflow-demo",
    displayName: "Eduflow",
    category: "Education",
    industry: "services", // Fallback from education
    businessModel: "Courses",
    primaryUseCase: "Online Courses / LMS",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Complete Learning Management System.",
      bullets: [
        "Course curriculum outline",
        "Video lesson player",
        "Progress tracking",
      ],
      bestFor: ["Educators", "Coaches", "Training Centers"],
      keyModules: ["LMS Player", "Student Progress", "Quizzes"],
    },
    routes: ["/", "/learn/:courseId"],
    layoutKey: "SkillAcademyCourses",
    onboardingProfile: {
      prefill: {
        industryCategory: "education",
        deliveryEnabled: false,
        paymentsEnabled: true,
      },
      skipSteps: ["logistics"],
      requireSteps: ["finance"],
    },
  },
  "vayva-gym-flow": {
    templateId: "vayva-gym-flow",
    slug: "gym-demo",
    displayName: "Gym Flow",
    category: "Service",
    industry: "services",
    businessModel: "Service",
    primaryUseCase: "Fitness / Gym",
    requiredPlan: "free",
    defaultTheme: "dark",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Class bookings and memberships.",
      bullets: ["Class calendar", "Membership plans", "Trainer profiles"],
      bestFor: ["Gyms", "Yoga Studios"],
      keyModules: ["Calendar", "Memberships"],
    },
    routes: ["/"],
    layoutKey: "StandardServiceHome",
    onboardingProfile: { prefill: { industryCategory: "services" } },
  },
  "vayva-law-firm": {
    templateId: "vayva-law-firm",
    slug: "law-demo",
    displayName: "Legal Partners",
    category: "Service",
    industry: "services",
    businessModel: "Service",
    primaryUseCase: "Professional Services",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Trustworthy presence for professionals.",
      bullets: ["Practice areas", "Team bios", "Consultation form"],
      bestFor: ["Law Firms", "Accountants"],
      keyModules: ["Consultation Request", "Team Profiles"],
    },
    routes: ["/"],
    layoutKey: "StandardServiceHome",
    onboardingProfile: { prefill: { industryCategory: "services" } },
  },
  "vayva-clean-crew": {
    templateId: "vayva-clean-crew",
    slug: "clean-demo",
    displayName: "Clean Crew",
    category: "Service",
    industry: "services",
    businessModel: "Service",
    primaryUseCase: "Home Services",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Home services on demand.",
      bullets: ["Service selection", "Zip code check", "Recurring plans"],
      bestFor: ["Cleaners", "Plumbers", "Handymen"],
      keyModules: ["Location Check", "Subscriptions"],
    },
    routes: ["/"],
    layoutKey: "StandardServiceHome",
    onboardingProfile: { prefill: { industryCategory: "services" } },
  },
};
