export const SPECIALIZED_TEMPLATES = {
  "vayva-file-vault": {
    templateId: "vayva-file-vault",
    slug: "filevault-demo",
    displayName: "FileVault",
    category: "Digital",
    industry: "digital",
    businessModel: "Digital",
    primaryUseCase: "Digital Downloads",
    requiredPlan: "free",
    defaultTheme: "dark",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Secure delivery for digital assets.",
      bullets: [
        "Instant secure download links",
        "License key distribution",
        "Preview for audio/video/pdf",
      ],
      bestFor: ["E-book authors", "Software devs", "Digital artists"],
      keyModules: [
        "Digital Rights Management",
        "Secure Links",
        "Automated Email",
      ],
    },
    routes: ["/"],
    layoutKey: "StandardDigitalHome",
    onboardingProfile: {
      prefill: {
        industryCategory: "digital",
        deliveryEnabled: false,
        paymentsEnabled: true,
      },
      skipSteps: ["logistics"],
      requireSteps: ["finance"],
    },
  },
  "vayva-ticketly": {
    templateId: "vayva-ticketly",
    slug: "ticketly-demo",
    displayName: "Ticketly",
    category: "Events",
    industry: "events",
    businessModel: "Events",
    primaryUseCase: "Ticketing / RSVPs",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Event ticketing and guest management.",
      bullets: [
        "Tiered ticket types (VIP, Early Bird)",
        "Event schedule display",
        "QR code generation",
      ],
      bestFor: ["Concerts", "Workshops", "Conferences"],
      keyModules: ["Ticketing Engine", "QR Check-in", "Guest Lists"],
    },
    routes: ["/", "/events/:slug"],
    layoutKey: "StandardEventsHome",
    onboardingProfile: {
      prefill: {
        industryCategory: "events",
        deliveryEnabled: false,
        paymentsEnabled: true,
      },
      skipSteps: ["logistics"],
      requireSteps: ["finance"],
    },
  },
  "vayva-bulktrade": {
    templateId: "vayva-bulktrade",
    slug: "bulktrade-demo",
    displayName: "BulkTrade",
    category: "B2B",
    industry: "b2b",
    businessModel: "Wholesale",
    primaryUseCase: "Wholesale / Bulk Orders",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "B2B portal for high-volume trade.",
      bullets: [
        "Minimum Order Quantity (MOQ) rules",
        "Tiered volume pricing tables",
        "Request for Quote (RFQ) flow",
      ],
      bestFor: ["Wholesalers", "Manufacturers", "Distributors"],
      keyModules: ["RFQ System", "Volume Pricing", "Invoice Generation"],
    },
    routes: ["/"],
    layoutKey: "BulkTradeHome",
    onboardingProfile: {
      prefill: {
        industryCategory: "b2b",
        deliveryEnabled: true,
        paymentsEnabled: true,
      },
      requireSteps: ["finance", "kyc"],
    },
  },
  "vayva-markethub": {
    templateId: "vayva-markethub",
    slug: "markethub-demo",
    displayName: "MarketHub",
    category: "Marketplace",
    industry: "retail", // Fallback from marketplace
    businessModel: "Marketplace",
    primaryUseCase: "Multi-vendor",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Launch your own multi-vendor platform.",
      bullets: [
        "Vendor profiles and catalogs",
        "Unified cart from multiple sellers",
        "Vendor rating system",
        "Commission engine",
      ],
      bestFor: ["Niche marketplaces", "Aggregators", "Malls"],
      keyModules: [
        "Multi-vendor Payouts",
        "Vendor Portal",
        "Commission Engine",
      ],
    },
    routes: ["/"],
    layoutKey: "CreativeMarketStore",
    onboardingProfile: {
      prefill: {
        industryCategory: "marketplace",
        deliveryEnabled: true,
        paymentsEnabled: true,
      },
      requireSteps: ["finance", "kyc"],
    },
  },
  "vayva-giveflow": {
    templateId: "vayva-giveflow",
    slug: "giveflow-demo",
    displayName: "GiveFlow",
    category: "Nonprofit",
    industry: "nonprofit",
    businessModel: "Donations",
    primaryUseCase: "Fundraising / Charity",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Drive impact with donation campaigns.",
      bullets: [
        "Fundraising goal progress bars",
        "Recurring donation options",
        "Donor wall recognition",
      ],
      bestFor: ["Non-profits", "Charities", "Personal Causes"],
      keyModules: ["Donations", "Recurring Billing", "Goal Tracking"],
    },
    routes: ["/"],
    layoutKey: "GiveFlowHome",
    onboardingProfile: {
      prefill: {
        industryCategory: "nonprofit",
        deliveryEnabled: false,
        paymentsEnabled: true,
      },
      skipSteps: ["logistics"],
      requireSteps: ["finance"],
    },
  },
  "vayva-homelist": {
    templateId: "vayva-homelist",
    slug: "homelist-demo",
    displayName: "HomeList",
    category: "Real Estate",
    industry: "real_estate",
    businessModel: "Property",
    primaryUseCase: "Listings / Rentals",
    requiredPlan: "free",
    defaultTheme: "light",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Showcase properties and capture leads.",
      bullets: [
        "Property search with advanced filters",
        "Map integration for locations",
        "Booking viewing appointments",
      ],
      bestFor: ["Real Estate Agents", "Property Managers", "Rental Listings"],
      keyModules: ["Property Listings", "Map View", "Lead Capture Form"],
    },
    routes: ["/", "/properties/*"],
    layoutKey: "HomeListHome",
    onboardingProfile: {
      prefill: {
        industryCategory: "real_estate",
        deliveryEnabled: false,
        paymentsEnabled: false,
      },
      skipSteps: ["logistics", "finance"],
    },
  },
  "vayva-noir-club": {
    templateId: "vayva-noir-club",
    slug: "noir-club-demo",
    displayName: "Noir Club",
    category: "Nightlife",
    industry: "nightlife",
    businessModel: "Venue",
    primaryUseCase: "Clubs & Lounges",
    requiredPlan: "free",
    defaultTheme: "dark",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Premium nightclub experience.",
      bullets: [
        "Immersive dark theme with gold accents",
        "Table reservation with bottle pre-orders",
        "VIP section showcase",
        "Event calendar integration",
      ],
      bestFor: ["Nightclubs", "Lounges", "VIP venues"],
      keyModules: [
        "Table Booking",
        "Bottle Menu",
        "Event Listings",
        "Guest List",
      ],
    },
    routes: ["/", "/events", "/tables", "/bottles", "/reserve"],
    layoutKey: "NoirClubHome",
    componentProps: {
      heroText: "EXPERIENCE\nTHE NIGHT",
      heroSubtext: "Premium Tables • Bottle Service • Unforgettable Nights",
    },
    onboardingProfile: {
      prefill: {
        industryCategory: "nightlife",
        deliveryEnabled: false,
        paymentsEnabled: true,
      },
      requireSteps: ["venue_profile", "table_setup", "bottle_menu"],
    },
  },
  "vayva-pulse-events": {
    templateId: "vayva-pulse-events",
    slug: "pulse-events-demo",
    displayName: "Pulse Events",
    category: "Nightlife",
    industry: "nightlife",
    businessModel: "Promoter",
    primaryUseCase: "Event Promoters",
    requiredPlan: "free",
    defaultTheme: "dark",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Event promotion made powerful.",
      bullets: [
        "Bold event showcase with countdown timers",
        "Multi-tier ticket sales",
        "Past event gallery for credibility",
        "Social proof and testimonials",
      ],
      bestFor: ["Event promoters", "Party organizers", "Concert promoters"],
      keyModules: [
        "Ticket Sales",
        "Event Gallery",
        "Countdown Timer",
        "Social Sharing",
      ],
    },
    routes: ["/", "/events/:slug", "/tickets", "/gallery"],
    layoutKey: "PulseEventsHome",
    componentProps: {
      heroText: "UNFORGETTABLE\nNIGHTS",
      heroSubtext: "Tickets • Events • Experiences",
    },
    onboardingProfile: {
      prefill: {
        industryCategory: "nightlife",
        deliveryEnabled: false,
        paymentsEnabled: true,
      },
      requireSteps: ["promoter_profile", "first_event"],
    },
  },
  "vayva-velvet-lounge": {
    templateId: "vayva-velvet-lounge",
    slug: "velvet-lounge-demo",
    displayName: "Velvet Lounge",
    category: "Nightlife",
    industry: "nightlife",
    businessModel: "Venue",
    primaryUseCase: "Upscale Lounges",
    requiredPlan: "starter",
    defaultTheme: "dark",
    status: "active",
    preview: { thumbnailUrl: null, mobileUrl: null, desktopUrl: null },
    compare: {
      headline: "Luxury lounge sophistication.",
      bullets: [
        "Elegant burgundy and gold design",
        "Interactive table map selection",
        "Premium bottle showcase",
        "Dress code and ambiance highlights",
      ],
      bestFor: ["Upscale lounges", "Rooftop bars", "Speakeasies"],
      keyModules: [
        "Table Map",
        "Bottle Catalog",
        "Reservation System",
        "Dress Code",
      ],
    },
    routes: ["/", "/reserve", "/menu", "/events", "/gallery"],
    layoutKey: "VelvetLoungeHome",
    componentProps: {
      heroText: "ELEVATE\nYOUR NIGHT",
      heroSubtext: "Exclusive Tables • Premium Spirits • Refined Atmosphere",
    },
    onboardingProfile: {
      prefill: {
        industryCategory: "nightlife",
        deliveryEnabled: false,
        paymentsEnabled: true,
      },
      requireSteps: ["venue_profile", "table_setup", "bottle_menu"],
    },
  },
};
