import { NextRequest, NextResponse } from "next/server";
import { withVayvaAPI } from "@/lib/api-handler";
import { PERMISSIONS } from "@/lib/team/permissions";
import { prisma } from "@vayva/db";
import { logger } from "@vayva/shared";

// GET /api/realestate/agents/[id]/performance - Get agent performance metrics
export const GET = withVayvaAPI(
  PERMISSIONS.DASHBOARD_VIEW,
  async (req: NextRequest, { storeId, params }: { storeId: string; params: Promise<{ id: string }> }) => {
    try {
      const { id } = await params;
      const { searchParams } = new URL(req.url);
      const from = searchParams.get("from");
      const to = searchParams.get("to");

      const fromDate = from ? new Date(from) : new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
      const toDate = to ? new Date(to) : new Date();

      // Get all properties associated with this agent
      const agentProperties = await prisma.property.findMany({
        where: {
          storeId,
          agentId: id
        },
        select: {
          id: true,
          price: true,
          status: true,
          purpose: true,
          createdAt: true,
          updatedAt: true
        }
      });

      // Calculate sales metrics
      const soldProperties = agentProperties.filter(p => p.status === 'sold' || p.status === 'rented');
      const activeListings = agentProperties.filter(p => p.status === 'available');
      const pendingProperties = agentProperties.filter(p => p.status === 'pending');

      // Calculate total sales volume
      const totalSalesVolume = soldProperties.reduce((sum, prop) => {
        return sum + Number(prop.price);
      }, 0);

      // Calculate commission (assuming 3% standard rate)
      const commissionRate = 0.03;
      const totalCommission = totalSalesVolume * commissionRate;

      // Get leads assigned to this agent
      const agentLeads = await prisma.realEstateLead.findMany({
        where: {
          merchantId: storeId,
          agentId: id
        },
        select: {
          id: true,
          status: true,
          type: true,
          budgetMax: true,
          createdAt: true,
          scores: {
            orderBy: { calculatedAt: 'desc' },
            take: 1
          }
        }
      });

      // Calculate lead metrics
      const totalLeads = agentLeads.length;
      const convertedLeads = agentLeads.filter(l => l.status === 'converted').length;
      const leadConversionRate = totalLeads > 0 ? (convertedLeads / totalLeads) * 100 : 0;

      // Get showings for this agent
      const agentShowings = await prisma.propertyShowing.findMany({
        where: {
          merchantId: storeId,
          agentId: id,
          scheduledAt: {
            gte: fromDate,
            lte: toDate
          }
        },
        select: {
          id: true,
          status: true,
          type: true,
          scheduledAt: true
        }
      });

      const totalShowings = agentShowings.length;
      const completedShowings = agentShowings.filter(s => s.status === 'completed').length;
      const showingNoShows = agentShowings.filter(s => s.status === 'no_show').length;

      // Get CMA reports generated by this agent
      const agentCMAs = await prisma.cMAReport.count({
        where: {
          merchantId: storeId,
          agentId: id,
          generatedAt: {
            gte: fromDate,
            lte: toDate
          }
        }
      });

      // Calculate average metrics
      const avgSalePrice = soldProperties.length > 0 
        ? soldProperties.reduce((sum, prop) => sum + Number(prop.price), 0) / soldProperties.length 
        : 0;

      // Get recent transactions
      const recentTransactions = soldProperties
        .filter(p => p.updatedAt >= fromDate && p.updatedAt <= toDate)
        .sort((a, b) => b.updatedAt.getTime() - a.updatedAt.getTime())
        .slice(0, 10)
        .map(p => ({
          id: p.id,
          price: Number(p.price),
          status: p.status,
          purpose: p.purpose,
          closedAt: p.updatedAt
        }));

      // Performance trends (compare to previous period)
      const previousFrom = new Date(fromDate.getTime() - (toDate.getTime() - fromDate.getTime()));
      const previousTo = fromDate;

      const [previousSold, previousLeads] = await Promise.all([
        prisma.property.count({
          where: {
            storeId,
            agentId: id,
            status: { in: ['sold', 'rented'] },
            updatedAt: {
              gte: previousFrom,
              lte: previousTo
            }
          }
        }),
        prisma.realEstateLead.count({
          where: {
            merchantId: storeId,
            agentId: id,
            createdAt: {
              gte: previousFrom,
              lte: previousTo
            }
          }
        })
      ]);

      const salesGrowth = previousSold > 0 
        ? ((soldProperties.length - previousSold) / previousSold) * 100 
        : 0;

      const leadsGrowth = previousLeads > 0 
        ? ((totalLeads - previousLeads) / previousLeads) * 100 
        : 0;

      return NextResponse.json({
        success: true,
        data: {
          agentId: id,
          period: {
            from: fromDate.toISOString(),
            to: toDate.toISOString()
          },
          listings: {
            total: agentProperties.length,
            active: activeListings.length,
            pending: pendingProperties.length,
            sold: soldProperties.length
          },
          sales: {
            totalVolume: totalSalesVolume,
            count: soldProperties.length,
            averagePrice: avgSalePrice,
            commission: totalCommission,
            growth: salesGrowth
          },
          leads: {
            total: totalLeads,
            converted: convertedLeads,
            conversionRate: leadConversionRate,
            growth: leadsGrowth
          },
          showings: {
            total: totalShowings,
            completed: completedShowings,
            noShows: showingNoShows,
            completionRate: totalShowings > 0 ? (completedShowings / totalShowings) * 100 : 0
          },
          cmas: {
            total: agentCMAs
          },
          recentTransactions,
          performance: {
            overall: calculateOverallPerformance(soldProperties.length, totalLeads, leadConversionRate, totalShowings)
          }
        }
      });
    } catch (error: unknown) {
      logger.error("[AGENT_PERFORMANCE_ERROR]", { 
        error: error instanceof Error ? error.message : String(error),
        storeId 
      });
      return NextResponse.json(
        { success: false, error: "Failed to fetch agent performance" },
        { status: 500 }
      );
    }
  }
);

function calculateOverallPerformance(sales: number, leads: number, conversionRate: number, showings: number): number {
  // Simple weighted scoring (0-100)
  const salesScore = Math.min(100, sales * 10); // 10 points per sale
  const leadScore = Math.min(100, leads * 5); // 5 points per lead
  const conversionScore = conversionRate; // Already 0-100
  const showingScore = Math.min(100, showings * 3); // 3 points per showing

  return Math.round((salesScore * 0.4 + leadScore * 0.2 + conversionScore * 0.3 + showingScore * 0.1));
}
