import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from "react";
import Link from "next/link";
import { cn } from "../utils";
import { Button } from "./Button";
import { Icon } from "./Icon";
export function PageHeader({ title, description, breadcrumbs, leadingIcon, primaryAction, secondaryAction, rightSlot, className, }) {
    return (_jsxs("div", { className: cn("flex flex-col gap-4", className), children: [breadcrumbs && breadcrumbs.length > 0 && (_jsx("nav", { "aria-label": "Breadcrumb", className: "flex flex-wrap items-center gap-2 text-xs text-text-tertiary", children: breadcrumbs.map((b, idx) => (_jsxs(React.Fragment, { children: [b.href ? (_jsx(Link, { href: b.href, className: "hover:text-text-secondary transition-colors", children: b.label })) : (_jsx("span", { className: "text-text-secondary", children: b.label })), idx < breadcrumbs.length - 1 && (_jsx("span", { className: "text-text-tertiary", children: "/" }))] }, `${b.label}-${idx}`))) })), _jsxs("div", { className: "flex flex-col gap-4 md:flex-row md:items-end md:justify-between", children: [_jsxs("div", { className: "flex items-start gap-4 min-w-0", children: [leadingIcon && (_jsx("div", { className: "h-12 w-12 rounded-2xl bg-status-success/10 border border-border flex items-center justify-center shrink-0", children: _jsx(Icon, { name: leadingIcon, className: "text-status-success", size: 22 }) })), _jsxs("div", { className: "min-w-0", children: [_jsx("h1", { className: "text-2xl sm:text-3xl font-heading font-bold tracking-tight text-text-primary truncate", children: title }), description && (_jsx("p", { className: "mt-1 text-sm text-text-secondary max-w-2xl", children: description }))] })] }), _jsxs("div", { className: "flex items-center gap-2 flex-wrap justify-start md:justify-end", children: [rightSlot, secondaryAction && (_jsxs(Button, { variant: "outline", onClick: secondaryAction.onClick, className: "rounded-xl", children: [secondaryAction.icon && (_jsx(Icon, { name: secondaryAction.icon, size: 16 })), secondaryAction.label] })), primaryAction && (_jsxs(Button, { onClick: primaryAction.onClick, className: "rounded-xl", children: [primaryAction.icon && (_jsx(Icon, { name: primaryAction.icon, size: 16 })), primaryAction.label] }))] })] })] }));
}
