import type { IndustryDashboardDefinition } from '@vayva/industry-core';

export const BEAUTY_DASHBOARD: IndustryDashboardDefinition = {
  industry: 'beauty',
  title: 'Beauty Operations',
  subtitle: 'Manage appointments, staff, and client experience',
  primaryObjectLabel: 'Appointment',
  kpis: [
    {
      id: 'today_appointments',
      label: "Today's Appointments",
      icon: 'Calendar',
      queryType: 'count',
      entityType: 'appointments',
      filters: { date: 'today' },
      trendMetric: 'vs_last_week',
      color: 'blue',
    },
    {
      id: 'revenue_today',
      label: "Today's Revenue",
      icon: 'DollarSign',
      queryType: 'sum',
      entityType: 'appointments',
      field: 'totalAmount',
      filters: { date: 'today', status: ['completed'] },
      format: 'currency',
      trendMetric: 'vs_yesterday',
      color: 'green',
    },
    {
      id: 'active_clients',
      label: 'Active Clients (30d)',
      icon: 'Users',
      queryType: 'count',
      entityType: 'clients',
      filters: { lastVisit: 'last_30_days' },
      trendMetric: 'vs_previous_30d',
      color: 'purple',
    },
    {
      id: 'staff_utilization',
      label: 'Staff Utilization',
      icon: 'Clock',
      queryType: 'percentage',
      entityType: 'appointments',
      calculation: 'booked_hours / available_hours',
      filters: { date: 'today' },
      format: 'percentage',
      target: 75,
      color: 'orange',
    },
  ],
  widgets: [
    {
      id: 'appointment_calendar',
      title: "Today's Schedule",
      type: 'calendar',
      size: { width: 2, height: 2 },
      dataSource: {
        type: 'appointments',
        filters: { date: 'today', status: ['scheduled', 'confirmed', 'in_progress'] },
      },
      actions: [
        { label: 'Check In', action: 'check_in' },
        { label: 'Reschedule', action: 'reschedule' },
        { label: 'Cancel', action: 'cancel' },
      ],
    },
    {
      id: 'staff_status',
      title: 'Staff Status',
      type: 'list',
      size: { width: 1, height: 2 },
      dataSource: {
        type: 'staff',
        fields: ['name', 'currentAppointments', 'nextAvailable', 'todayRevenue'],
      },
      display: {
        showAvatar: true,
        showStatus: true,
        highlightTopPerformers: true,
      },
    },
    {
      id: 'upcoming_appointments',
      title: 'Upcoming This Week',
      type: 'table',
      size: { width: 2, height: 1 },
      dataSource: {
        type: 'appointments',
        filters: { dateRange: 'next_7_days' },
        limit: 10,
      },
      columns: ['time', 'client', 'service', 'staff', 'status'],
      actions: [{ label: 'Confirm', action: 'confirm' }],
    },
    {
      id: 'client_insights',
      title: 'Client Insights',
      type: 'chart',
      size: { width: 1, height: 1 },
      chartType: 'bar',
      dataSource: {
        type: 'appointments',
        groupBy: 'day',
        metric: 'count',
        dateRange: 'last_7_days',
      },
    },
    {
      id: 'popular_services',
      title: 'Popular Services',
      type: 'ranking',
      size: { width: 1, height: 1 },
      dataSource: {
        type: 'services',
        metric: 'bookings_count',
        dateRange: 'last_30_days',
        limit: 5,
      },
    },
    {
      id: 'revenue_trend',
      title: 'Revenue Trend',
      type: 'chart',
      size: { width: 2, height: 1 },
      chartType: 'line',
      dataSource: {
        type: 'appointments',
        groupBy: 'day',
        metric: 'sum(totalAmount)',
        dateRange: 'last_30_days',
      },
    },
  ],
  quickActions: [
    {
      id: 'new_appointment',
      label: 'New Appointment',
      icon: 'Plus',
      action: '/dashboard/appointments/new',
      color: 'blue',
    },
    {
      id: 'add_client',
      label: 'Add Client',
      icon: 'UserPlus',
      action: '/dashboard/clients/new',
      color: 'green',
    },
    {
      id: 'manage_staff',
      label: 'Manage Staff',
      icon: 'Users',
      action: '/dashboard/staff',
      color: 'purple',
    },
    {
      id: 'service_menu',
      label: 'Service Menu',
      icon: 'List',
      action: '/dashboard/services',
      color: 'orange',
    },
  ],
  alerts: [
    {
      id: 'no_show_alert',
      trigger: {
        entity: 'appointments',
        condition: 'status == "no_show"',
        timeframe: 'today',
      },
      severity: 'medium',
      message: 'No-show detected - consider sending follow-up',
      action: 'send_follow_up',
    },
    {
      id: 'low_staff_utilization',
      trigger: {
        entity: 'staff',
        condition: 'utilization < 50%',
        timeframe: 'today',
      },
      severity: 'low',
      message: 'Low staff utilization today',
      action: 'view_schedule',
    },
  ],
};

export const BEAUTY_DASHBOARD_CONFIG = BEAUTY_DASHBOARD;
