/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ url: string; revision: string | null }>;
};

interface PushPayload {
  title?: string;
  body?: string;
  tag?: string;
}

function isPushPayload(value: unknown): value is PushPayload {
  return typeof value === 'object' && value !== null;
}

// Clean up old caches
cleanupOutdatedCaches();

// Precache static assets (generated by Next.js)
precacheAndRoute(self.__WB_MANIFEST);

// Cache strategy for API requests - Network First with fallback
registerRoute(
  ({ url }: { url: URL }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60, // 1 hour
      }),
    ],
  })
);

// Cache strategy for images - Cache First
registerRoute(
  ({ request, url }: { request: Request; url: URL }) =>
    request.destination === 'image' || 
    url.pathname.endsWith('.png') ||
    url.pathname.endsWith('.jpg') ||
    url.pathname.endsWith('.webp'),
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Cache strategy for fonts - Cache First
registerRoute(
  ({ request, url }: { request: Request; url: URL }) =>
    request.destination === 'font' ||
    url.pathname.includes('fonts'),
  new CacheFirst({
    cacheName: 'fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// Cache strategy for static assets (CSS, JS) - Stale While Revalidate
registerRoute(
  ({ request, url }: { request: Request; url: URL }) =>
    request.destination === 'style' ||
    request.destination === 'script',
  new StaleWhileRevalidate({
    cacheName: 'static-assets-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Background sync for failed API requests (e.g., when offline)
const bgSyncPlugin = new BackgroundSyncPlugin('saas-api-queue', {
  maxRetentionTime: 24 * 60, // Retry for up to 24 hours
});

registerRoute(
  ({ url }: { url: URL }) => url.pathname.startsWith('/api/saas/'),
  new NetworkFirst({
    cacheName: 'saas-api-cache',
    plugins: [bgSyncPlugin],
  }),
  'POST'
);

// Handle messages from main thread
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Push notification handling (for future real-time alerts)
self.addEventListener('push', (event) => {
  let data: unknown = {};
  try {
    data = event.data?.json() ?? {};
  } catch {
    data = {};
  }
  const payload = isPushPayload(data) ? data : {};
  const title = payload.title || 'SaaS Dashboard Update';
  const options = {
    body: payload.body || 'New metrics available',
    icon: '/icon-192x192.png',
    badge: '/badge-72x72.png',
    tag: payload.tag || 'saas-metrics',
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

// Notification click handling
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((clientList) => {
      // Focus existing window if available
      for (const client of clientList) {
        if (client.url === '/dashboard/saas' && 'focus' in client) {
          return client.focus();
        }
      }
      // Open new window if none exists
      if (self.clients.openWindow) {
        return self.clients.openWindow('/dashboard/saas');
      }
    })
  );
});
