import { NextRequest, NextResponse } from "next/server";
import { withVayvaAPI, APIContext } from "@/lib/api-handler";
import { PERMISSIONS } from "@/lib/team/permissions";
import { standardHeaders } from "@vayva/shared";
import { prisma } from "@vayva/db";
import { z } from "zod";

const PDFExportSchema = z.object({
  type: z.enum(["orders", "inventory", "customers", "sales_report"]),
  title: z.string(),
  dateRange: z.object({
    from: z.string(),
    to: z.string(),
  }),
  filters: z.record(z.any()).optional(),
  includeCharts: z.boolean().default(false),
});

// POST /api/retail/export/pdf - Generate PDF report
export const POST = withVayvaAPI(
  PERMISSIONS.RETAIL_INVENTORY_VIEW,
  async (req: NextRequest, { storeId, correlationId }: APIContext) => {
    const requestId = correlationId;
    
    try {
      const body = await req.json();
      const result = PDFExportSchema.safeParse(body);

      if (!result.success) {
        return NextResponse.json(
          {
            error: "Invalid request",
            details: result.error.flatten(),
          },
          { status: 400, headers: standardHeaders(requestId) },
        );
      }

      const { type, title, dateRange, filters, includeCharts } = result.data;

      // Fetch data for report
      const reportData = await fetchReportData(storeId, type, dateRange, filters);

      // Generate PDF HTML content
      const htmlContent = generatePDFHTML(type, title, reportData, dateRange, includeCharts);

      // In production, use a library like puppeteer or pdfkit
      // For now, return HTML that can be converted to PDF
      return NextResponse.json(
        {
          success: true,
          data: {
            html: htmlContent,
            metadata: {
              type,
              title,
              generatedAt: new Date().toISOString(),
              itemCount: reportData.length,
            },
          },
          message: "PDF generated. Use the HTML content with a PDF converter.",
        },
        { status: 200, headers: standardHeaders(requestId) },
      );
    } catch (error) {
      console.error("PDF export error:", error);
      return NextResponse.json(
        { error: "Failed to generate PDF" },
        { status: 500, headers: standardHeaders(requestId) },
      );
    }
  },
);

function generatePDFHTML(
  type: string,
  title: string,
  data: any[],
  dateRange: any,
  includeCharts: boolean
): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; }
    h1 { color: #333; border-bottom: 2px solid #3B82F6; padding-bottom: 10px; }
    .metadata { margin-bottom: 30px; color: #666; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { background: #3B82F6; color: white; padding: 12px; text-align: left; }
    td { padding: 10px; border-bottom: 1px solid #ddd; }
    tr:nth-child(even) { background: #f9f9f9; }
    .summary { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin: 20px 0; }
    .card { background: #f0f9ff; padding: 20px; border-radius: 8px; }
    .card-value { font-size: 24px; font-weight: bold; color: #3B82F6; }
    .card-label { font-size: 12px; color: #666; margin-top: 5px; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  
  <div class="metadata">
    <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
    <p><strong>Period:</strong> ${new Date(dateRange.from).toLocaleDateString()} - ${new Date(dateRange.to).toLocaleDateString()}</p>
    <p><strong>Total Records:</strong> ${data.length}</p>
  </div>

  ${generateSummaryCards(type, data)}

  <h2>Detailed Data</h2>
  ${generateTable(type, data)}

  ${includeCharts ? '<div class="charts"><!-- Charts would be rendered here --></div>' : ''}

  <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px;">
    <p>Generated by Vayva Retail Dashboard</p>
  </div>
</body>
</html>
  `;
}

function generateSummaryCards(type: string, data: any[]): string {
  if (type === "orders") {
    const totalRevenue = data.reduce((sum: any, order: any) => sum + (order.totalAmount || 0), 0);
    const avgOrderValue = data.length > 0 ? totalRevenue / data.length : 0;
    
    return `
      <div class="summary">
        <div class="card">
          <div class="card-value">${data.length}</div>
          <div class="card-label">Total Orders</div>
        </div>
        <div class="card">
          <div class="card-value">$${totalRevenue.toFixed(2)}</div>
          <div class="card-label">Total Revenue</div>
        </div>
        <div class="card">
          <div class="card-value">$${avgOrderValue.toFixed(2)}</div>
          <div class="card-label">Avg Order Value</div>
        </div>
      </div>
    `;
  }

  if (type === "inventory") {
    const totalItems = data.reduce((sum: any, item: any) => sum + (item.quantity || 0), 0);
    const lowStockItems = data.filter((item: any) => item.status === "Low Stock").length;
    
    return `
      <div class="summary">
        <div class="card">
          <div class="card-value">${totalItems}</div>
          <div class="card-label">Total Units in Stock</div>
        </div>
        <div class="card">
          <div class="card-value">${data.length}</div>
          <div class="card-label">Unique Products</div>
        </div>
        <div class="card">
          <div class="card-value">${lowStockItems}</div>
          <div class="card-label">Low Stock Alerts</div>
        </div>
      </div>
    `;
  }

  return "";
}

function generateTable(type: string, data: any[]): string {
  let columns: Array<{ key: string; label: string }> = [];

  switch (type) {
    case "orders":
      columns = [
        { key: "orderNumber", label: "Order #" },
        { key: "customerName", label: "Customer" },
        { key: "channel", label: "Channel" },
        { key: "status", label: "Status" },
        { key: "totalAmount", label: "Amount" },
        { key: "createdAt", label: "Date" },
      ];
      break;
    case "inventory":
      columns = [
        { key: "productName", label: "Product" },
        { key: "sku", label: "SKU" },
        { key: "quantity", label: "Stock" },
        { key: "reorderPoint", label: "Reorder Point" },
        { key: "status", label: "Status" },
      ];
      break;
    case "customers":
      columns = [
        { key: "name", label: "Name" },
        { key: "email", label: "Email" },
        { key: "totalOrders", label: "Orders" },
        { key: "totalSpent", label: "Total Spent" },
      ];
      break;
  }

  const headers = columns.map((col) => `<th>${col.label}</th>`).join("");
  const rows = data
    .slice(0, 100) // Limit to 100 rows for PDF
    .map((item: any) => {
      const cells = columns
        .map((col) => {
          const value = item[col.key];
          const formatted = col.key.includes("Amount") || col.key.includes("Spent")
            ? `$${Number(value).toFixed(2)}`
            : col.key.includes("Date")
            ? new Date(value).toLocaleDateString()
            : String(value || "");
          return `<td>${formatted}</td>`;
        })
        .join("");
      return `<tr>${cells}</tr>`;
    })
    .join("");

  return `
    <table>
      <thead>${headers}</thead>
      <tbody>${rows}</tbody>
    </table>
  `;
}

async function fetchReportData(
  storeId: string,
  type: string,
  dateRange: any,
  filters?: any
): Promise<any[]> {
  const where: any = { storeId };

  if (dateRange?.from || dateRange?.to) {
    where.createdAt = {};
    if (dateRange.from) where.createdAt.gte = new Date(dateRange.from);
    if (dateRange.to) where.createdAt.lte = new Date(dateRange.to);
  }

  switch (type) {
    case "orders":
      if (filters?.status) where.status = filters.status;
      const orders = await prisma.order.findMany({
        where,
        include: { customer: true },
        orderBy: { createdAt: "desc" },
        take: 1000,
      });
      return orders.map((order) => ({
        orderNumber: order.orderNumber,
        customerName: order.customer?.name || "Guest",
        channel: order.channel,
        status: order.status,
        totalAmount: order.totalAmount,
        createdAt: order.createdAt,
      }));

    case "inventory":
      const inventory = await prisma.inventoryItem.findMany({
        where,
        include: { product: true },
        orderBy: { product: { name: "asc" } },
        take: 1000,
      });
      return inventory.map((item) => ({
        productName: item.product?.name || "Unknown",
        sku: item.sku,
        quantity: item.quantity,
        reorderPoint: item.reorderPoint,
        status: item.quantity <= item.reorderPoint ? "Low Stock" : "In Stock",
      }));

    case "customers":
      const customers = await prisma.customer.findMany({
        where,
        include: {
          loyaltyMember: true,
          _count: { select: { orders: true } },
        },
        orderBy: { totalSpent: "desc" },
        take: 1000,
      });
      return customers.map((customer) => ({
        name: customer.name,
        email: customer.email,
        totalOrders: customer._count.orders,
        totalSpent: customer.totalSpent || 0,
      }));

    default:
      return [];
  }
}
