/**
 * Integration Catalog
 * Pre-built integrations available in the marketplace
 */

import type { Integration, IntegrationCategory } from './types';

export const integrationCatalog: Integration[] = [
  // Accounting
  {
    id: 'quickbooks',
    name: 'QuickBooks',
    description: 'Sync orders, products, and financial data with QuickBooks Online. Automate bookkeeping and reconciliation.',
    category: 'accounting',
    logo: '/integrations/quickbooks.svg',
    rating: 4.8,
    reviewCount: 234,
    installCount: 1523,
    pricing: 'paid',
    setupType: 'oauth',
    features: [
      'Automatic order sync',
      'Product catalog sync',
      'Customer import',
      'Financial reporting',
      'Tax calculation',
      'Multi-currency support',
    ],
    developer: { name: 'Intuit', website: 'https://quickbooks.intuit.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'xero',
    name: 'Xero',
    description: 'Connect your store with Xero accounting software. Streamline invoicing and financial management.',
    category: 'accounting',
    logo: '/integrations/xero.svg',
    rating: 4.7,
    reviewCount: 189,
    installCount: 987,
    pricing: 'paid',
    setupType: 'oauth',
    features: [
      'Invoice generation',
      'Bank reconciliation',
      'Inventory tracking',
      'Payroll integration',
      'Multi-currency',
      'Reporting',
    ],
    developer: { name: 'Xero', website: 'https://www.xero.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Payments
  {
    id: 'paystack',
    name: 'Paystack',
    description: 'Accept payments from customers across Africa. Support for cards, bank transfers, USSD, and mobile money.',
    category: 'payments',
    logo: '/integrations/paystack.svg',
    rating: 4.9,
    reviewCount: 567,
    installCount: 3456,
    pricing: 'usage_based',
    setupType: 'api_key',
    features: [
      'Card payments',
      'Bank transfers',
      'USSD payments',
      'Mobile money',
      'QR code payments',
      'Split payments',
      'Subscriptions',
    ],
    developer: { name: 'Paystack', website: 'https://paystack.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'flutterwave',
    name: 'Flutterwave',
    description: 'Process payments from customers worldwide. 150+ currencies supported with local payment methods.',
    category: 'payments',
    logo: '/integrations/flutterwave.svg',
    rating: 4.7,
    reviewCount: 423,
    installCount: 2890,
    pricing: 'usage_based',
    setupType: 'api_key',
    features: [
      'International payments',
      '150+ currencies',
      'Local payment methods',
      'Fraud protection',
      'Recurring billing',
      'Payment links',
    ],
    developer: { name: 'Flutterwave', website: 'https://flutterwave.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Delivery
  {
    id: 'kwik',
    name: 'Kwik Delivery',
    description: 'Same-day delivery across Lagos and Abuja. Real-time tracking and instant dispatch.',
    category: 'delivery',
    logo: '/integrations/kwik.svg',
    rating: 4.6,
    reviewCount: 312,
    installCount: 1234,
    pricing: 'usage_based',
    setupType: 'api_key',
    features: [
      'Same-day delivery',
      'Real-time tracking',
      'Instant dispatch',
      'Multiple vehicle types',
      'Proof of delivery',
      'Cash on delivery',
    ],
    developer: { name: 'Kwik', website: 'https://kwik.delivery' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'gokada',
    name: 'Gokada',
    description: 'Fast delivery with Nigeria\'s leading last-mile delivery service. Bike and car options available.',
    category: 'delivery',
    logo: '/integrations/gokada.svg',
    rating: 4.5,
    reviewCount: 278,
    installCount: 987,
    pricing: 'usage_based',
    setupType: 'api_key',
    features: [
      'Last-mile delivery',
      'Bike delivery',
      'Car delivery',
      'Live tracking',
      'Delivery scheduling',
      'Return management',
    ],
    developer: { name: 'Gokada', website: 'https://gokada.ng' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Scheduling
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Sync appointments and events with Google Calendar. Automated scheduling and reminders.',
    category: 'scheduling',
    logo: '/integrations/google-calendar.svg',
    rating: 4.8,
    reviewCount: 445,
    installCount: 2134,
    pricing: 'free',
    setupType: 'oauth',
    features: [
      'Two-way sync',
      'Event creation',
      'Reminder notifications',
      'Availability checking',
      'Multiple calendars',
      'Team scheduling',
    ],
    developer: { name: 'Google', website: 'https://calendar.google.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'calendly',
    name: 'Calendly',
    description: 'Let customers book appointments directly. Eliminate back-and-forth scheduling emails.',
    category: 'scheduling',
    logo: '/integrations/calendly.svg',
    rating: 4.9,
    reviewCount: 389,
    installCount: 1567,
    pricing: 'free',
    setupType: 'oauth',
    features: [
      'Booking page',
      'Availability settings',
      'Automated reminders',
      'Time zone detection',
      'Buffer times',
      'Group events',
    ],
    developer: { name: 'Calendly', website: 'https://calendly.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Communication
  {
    id: 'zoom',
    name: 'Zoom',
    description: 'Add video conferencing to appointments and consultations. One-click meeting creation.',
    category: 'communication',
    logo: '/integrations/zoom.svg',
    rating: 4.8,
    reviewCount: 523,
    installCount: 1876,
    pricing: 'free',
    setupType: 'oauth',
    features: [
      'Video meetings',
      'Automatic links',
      'Meeting recordings',
      'Screen sharing',
      'Waiting rooms',
      'Meeting templates',
    ],
    developer: { name: 'Zoom', website: 'https://zoom.us' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    description: 'Integrate with Microsoft Teams for business communications and video calls.',
    category: 'communication',
    logo: '/integrations/teams.svg',
    rating: 4.6,
    reviewCount: 234,
    installCount: 876,
    pricing: 'free',
    setupType: 'oauth',
    features: [
      'Teams meetings',
      'Chat integration',
      'File sharing',
      'Channel notifications',
      'Calendar sync',
      'Collaboration',
    ],
    developer: { name: 'Microsoft', website: 'https://teams.microsoft.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // E-Signatures
  {
    id: 'docusign',
    name: 'DocuSign',
    description: 'Send, sign, and manage agreements electronically. Close deals faster with legally binding digital signatures.',
    category: 'esignature',
    logo: '/integrations/docusign.svg',
    rating: 4.9,
    reviewCount: 312,
    installCount: 876,
    pricing: 'paid',
    setupType: 'oauth',
    features: [
      'Electronic signatures',
      'Document templates',
      'Automated workflows',
      'Audit trail',
      'Mobile signing',
      'Bulk send',
    ],
    developer: { name: 'DocuSign', website: 'https://docusign.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Social Commerce
  {
    id: 'instagram-shop',
    name: 'Instagram Shopping',
    description: 'Sell directly on Instagram. Tag products in posts and stories to drive purchases from your followers.',
    category: 'social',
    logo: '/integrations/instagram.svg',
    rating: 4.8,
    reviewCount: 567,
    installCount: 2345,
    pricing: 'free',
    setupType: 'oauth',
    features: [
      'Product tagging',
      'Instagram Shop',
      'Story shopping',
      'Reels shopping',
      'Live shopping',
      'Catalog sync',
    ],
    developer: { name: 'Meta', website: 'https://instagram.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'facebook-shop',
    name: 'Facebook Shop',
    description: 'Create a Facebook Shop and sell products directly to your Facebook audience.',
    category: 'social',
    logo: '/integrations/facebook.svg',
    rating: 4.7,
    reviewCount: 423,
    installCount: 1987,
    pricing: 'free',
    setupType: 'oauth',
    features: [
      'Facebook Shop',
      'Product catalog',
      'Marketplace listings',
      'Order management',
      'Customer messaging',
      'Ads integration',
    ],
    developer: { name: 'Meta', website: 'https://facebook.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'tiktok-shop',
    name: 'TikTok Shop',
    description: 'Sell through TikTok videos and live streams. Reach millions of Gen Z shoppers.',
    category: 'social',
    logo: '/integrations/tiktok.svg',
    rating: 4.6,
    reviewCount: 234,
    installCount: 1234,
    pricing: 'usage_based',
    setupType: 'oauth',
    features: [
      'TikTok Shop',
      'Video commerce',
      'Live shopping',
      'Affiliate creator program',
      'Order management',
      'Catalog sync',
    ],
    developer: { name: 'TikTok', website: 'https://tiktok.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },

  // Email
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    description: 'Email marketing automation. Sync customers and send targeted campaigns.',
    category: 'email',
    logo: '/integrations/mailchimp.svg',
    rating: 4.7,
    reviewCount: 678,
    installCount: 2345,
    pricing: 'free',
    setupType: 'api_key',
    features: [
      'Customer sync',
      'Email campaigns',
      'Automation workflows',
      'A/B testing',
      'Analytics',
      'Templates',
    ],
    developer: { name: 'Mailchimp', website: 'https://mailchimp.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    description: 'Transactional email delivery. Reliable email infrastructure for order notifications.',
    category: 'email',
    logo: '/integrations/sendgrid.svg',
    rating: 4.8,
    reviewCount: 445,
    installCount: 1567,
    pricing: 'usage_based',
    setupType: 'api_key',
    features: [
      'Transactional email',
      'Email templates',
      'Delivery tracking',
      'Bounce handling',
      'Analytics',
      'API access',
    ],
    developer: { name: 'Twilio', website: 'https://sendgrid.com' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const getIntegrationById = (id: string): Integration | undefined => {
  return integrationCatalog.find(i => i.id === id);
};

export const getIntegrationsByCategory = (category: IntegrationCategory): Integration[] => {
  return integrationCatalog.filter(i => i.category === category);
};

export const searchIntegrations = (query: string): Integration[] => {
  const lowerQuery = query.toLowerCase();
  return integrationCatalog.filter(i =>
    i.name.toLowerCase().includes(lowerQuery) ||
    i.description.toLowerCase().includes(lowerQuery) ||
    i.features.some(f => f.toLowerCase().includes(lowerQuery))
  );
};

export const getAllCategories = (): IntegrationCategory[] => {
  return Array.from(new Set(integrationCatalog.map(i => i.category)));
};

export default integrationCatalog;
