import { NextRequest, NextResponse } from 'next/server';
import puppeteer from 'puppeteer-core';

/**
 * POST /api/reports/export/pdf
 * Generate PDF reports using Puppeteer
 * 
 * Environment variables:
 * - PUPPETEER_EXECUTABLE_PATH: Path to Chrome/Chromium binary
 * - PUPPETEER_WS_ENDPOINT: WebSocket endpoint for browser (optional, for services like Browserless)
 */

interface ReportData {
  type: 'project' | 'invoice' | 'analytics' | 'portfolio';
  title: string;
  content: string; // HTML content
  options?: PDFOptions;
}

interface PDFOptions {
  format?: 'A4' | 'Letter' | 'Legal';
  landscape?: boolean;
  printBackground?: boolean;
  margin?: {
    top: string;
    right: string;
    bottom: string;
    left: string;
  };
}

export async function POST(req: NextRequest) {
  try {
    const body: ReportData = await req.json();
    const { type, title, content, options = {} } = body;

    // Validate input
    if (!type || !title || !content) {
      return NextResponse.json(
        { error: 'Missing required fields: type, title, content' },
        { status: 400 }
      );
    }

    // Generate PDF
    const pdfBuffer = await generatePDF(content, {
      ...options,
      headerTemplate: getHeaderTemplate(title, type),
      footerTemplate: getFooterTemplate(),
    });

    // Return PDF as downloadable file
    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${sanitizeFilename(title)}.pdf"`,
        'Content-Length': pdfBuffer.length.toString(),
      },
    });
  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}

/**
 * Generate PDF using Puppeteer
 */
async function generatePDF(html: string, options: any): Promise<Buffer> {
  let browser;

  try {
    // Connect to browser
    browser = await connectBrowser();

    // Create page
    const page = await browser.newPage();

    // Set content with proper encoding
    await page.setContent(html, {
      waitUntil: 'networkidle0',
      encoding: 'utf-8',
    });

    // Generate PDF
    const pdfBuffer = await page.pdf({
      format: options.format || 'A4',
      landscape: options.landscape || false,
      printBackground: options.printBackground ?? true,
      margin: options.margin || {
        top: '20mm',
        right: '15mm',
        bottom: '20mm',
        left: '15mm',
      },
      displayHeaderFooter: true,
      headerTemplate: options.headerTemplate,
      footerTemplate: options.footerTemplate,
    });

    // Close page
    await page.close();

    return Buffer.from(pdfBuffer);
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}

/**
 * Connect to Puppeteer browser
 */
async function connectBrowser() {
  // Use remote browser service (Browserless, etc.)
  if (process.env.PUPPETEER_WS_ENDPOINT) {
    const puppeteer = await import('puppeteer-core');
    return puppeteer.connect({
      browserWSEndpoint: process.env.PUPPETEER_WS_ENDPOINT,
    });
  }

  // Use local Chrome/Chromium
  const executablePath = process.env.PUPPETEER_EXECUTABLE_PATH || '/usr/bin/chromium-browser';
  const puppeteer = await import('puppeteer-core');
  
  return puppeteer.launch({
    executablePath,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
    ],
  });
}

/**
 * Generate header template
 */
function getHeaderTemplate(title: string, type: string): string {
  return `
    <div style="font-size: 10px; width: 100%; padding: 5px 20px; border-bottom: 1px solid #e5e7eb;">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <div style="font-weight: bold; color: #4F46E5;">VAYVA</div>
        <div style="color: #6b7280;">
          ${type.charAt(0).toUpperCase() + type.slice(1)} Report • ${new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  `;
}

/**
 * Generate footer template with page numbers
 */
function getFooterTemplate(): string {
  return `
    <div style="font-size: 9px; width: 100%; padding: 5px 20px; border-top: 1px solid #e5e7eb;">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <div style="color: #6b7280;">Generated by Vayva Creative Agency Platform</div>
        <div style="color: #6b7280;">
          Page <span class="pageNumber"></span> of <span class="totalPages"></span>
        </div>
      </div>
    </div>
  `;
}

/**
 * Sanitize filename
 */
function sanitizeFilename(filename: string): string {
  return filename
    .replace(/[^a-z0-9]/gi, '_')
    .toLowerCase()
    .substring(0, 50);
}

/**
 * GET /api/reports/export/pdf?template=project&id=123
 * Generate PDF from predefined templates
 */
export async function GET(req: NextRequest) {
  const searchParams = req.nextUrl.searchParams;
  const template = searchParams.get('template');
  const id = searchParams.get('id');

  if (!template || !id) {
    return NextResponse.json(
      { error: 'Missing template or id parameter' },
      { status: 400 }
    );
  }

  try {
    // Fetch data based on template type
    let html: string;

    switch (template) {
      case 'project':
        html = await generateProjectReportHTML(id);
        break;
      case 'invoice':
        html = await generateInvoiceHTML(id);
        break;
      case 'analytics':
        html = await generateAnalyticsReportHTML(id);
        break;
      default:
        return NextResponse.json(
          { error: 'Invalid template type' },
          { status: 400 }
        );
    }

    // Generate and return PDF
    const pdfBuffer = await generatePDF(html, {});

    return new NextResponse(pdfBuffer, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${template}_${id}.pdf"`,
      },
    });
  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}

/**
 * Generate project report HTML template
 */
async function generateProjectReportHTML(projectId: string): Promise<string> {
  // In production: fetch project data from database
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; }
          .header { background: linear-gradient(135deg, #4F46E5 0%, #7C3AED 100%); color: white; padding: 40px; }
          .content { padding: 30px; }
          .section { margin: 30px 0; }
          .metric { display: inline-block; margin-right: 30px; text-align: center; }
          .metric-value { font-size: 32px; font-weight: bold; color: #4F46E5; }
          .metric-label { font-size: 14px; color: #6b7280; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
          th { background: #f9fafb; font-weight: 600; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Project Report</h1>
          <p>Website Redesign - Acme Corp</p>
        </div>
        <div class="content">
          <div class="section">
            <h2>Overview</h2>
            <p>Comprehensive project performance and metrics summary.</p>
          </div>
          
          <div class="section">
            <h2>Key Metrics</h2>
            <div class="metric">
              <div class="metric-value">$187K</div>
              <div class="metric-label">Revenue</div>
            </div>
            <div class="metric">
              <div class="metric-value">68%</div>
              <div class="metric-label">Profit Margin</div>
            </div>
            <div class="metric">
              <div class="metric-value">156h</div>
              <div class="metric-label">Hours Logged</div>
            </div>
          </div>

          <div class="section">
            <h2>Timeline</h2>
            <table>
              <thead>
                <tr>
                  <th>Milestone</th>
                  <th>Due Date</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Discovery</td>
                  <td>Feb 15, 2024</td>
                  <td>✓ Completed</td>
                </tr>
                <tr>
                  <td>Design</td>
                  <td>Mar 1, 2024</td>
                  <td>✓ Completed</td>
                </tr>
                <tr>
                  <td>Development</td>
                  <td>Apr 15, 2024</td>
                  <td>🔄 In Progress</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </body>
    </html>
  `;
}

/**
 * Generate invoice HTML template
 */
async function generateInvoiceHTML(invoiceId: string): Promise<string> {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: Arial, sans-serif; }
          .invoice-header { display: flex; justify-content: space-between; margin-bottom: 40px; }
          .invoice-title { font-size: 32px; font-weight: bold; color: #4F46E5; }
          .invoice-details { text-align: right; }
          table { width: 100%; border-collapse: collapse; }
          th { background: #4F46E5; color: white; padding: 12px; }
          td { padding: 12px; border-bottom: 1px solid #e5e7eb; }
          .total { font-size: 24px; font-weight: bold; text-align: right; margin-top: 20px; }
        </style>
      </head>
      <body>
        <div class="invoice-header">
          <div>
            <div class="invoice-title">INVOICE</div>
            <div>Invoice #: INV-001</div>
          </div>
          <div class="invoice-details">
            <div>Date: March 11, 2024</div>
            <div>Due: April 10, 2024</div>
          </div>
        </div>
        
        <table>
          <thead>
            <tr>
              <th>Description</th>
              <th>Quantity</th>
              <th>Rate</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Web Design Services</td>
              <td>40 hours</td>
              <td>$150/hr</td>
              <td>$6,000</td>
            </tr>
            <tr>
              <td>Development</td>
              <td>60 hours</td>
              <td>$125/hr</td>
              <td>$7,500</td>
            </tr>
          </tbody>
        </table>
        
        <div class="total">Total: $13,500</div>
      </body>
    </html>
  `;
}

/**
 * Generate analytics report HTML template
 */
async function generateAnalyticsReportHTML(storeId: string): Promise<string> {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: Arial, sans-serif; }
          .chart-placeholder { 
            background: #f9fafb; 
            border: 2px dashed #e5e7eb; 
            height: 300px; 
            display: flex; 
            align-items: center; 
            justify-content: center;
            margin: 20px 0;
          }
        </style>
      </head>
      <body>
        <h1>Analytics Report</h1>
        <p>Store ID: ${storeId}</p>
        <div class="chart-placeholder">
          Revenue Chart Would Appear Here
        </div>
      </body>
    </html>
  `;
}
