apiVersion: v1
kind: Service
metadata:
  name: vayva-api
  namespace: vayva
  labels:
    app: vayva-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: vayva-api
---
apiVersion: v1
kind: Service
metadata:
  name: vayva-api-blue
  namespace: vayva
  labels:
    app: vayva-api
    version: blue
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: vayva-api
    version: blue
---
apiVersion: v1
kind: Service
metadata:
  name: vayva-api-green
  namespace: vayva
  labels:
    app: vayva-api
    version: green
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: vayva-api
    version: green
