'use client';
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { useBusinessSettings, useDashboardSettings, useAISettings, useNotificationSettings } from '../providers/settings.provider';
import { toast } from 'sonner';
export function SettingsPanel({ isOpen, onClose }) {
    const { business, updateBusinessSettings } = useBusinessSettings();
    const { dashboard, updateDashboardSettings } = useDashboardSettings();
    const { ai, updateAISettings } = useAISettings();
    const { notifications, updateNotificationSettings } = useNotificationSettings();
    const [activeTab, setActiveTab] = useState('business');
    const [isSaving, setIsSaving] = useState(false);
    if (!isOpen)
        return null;
    const handleSave = async () => {
        setIsSaving(true);
        try {
            // All settings are saved automatically through the hooks
            // Just show success message
            toast.success('All settings saved successfully!');
        }
        catch (_error) {
            toast.error('Failed to save settings');
        }
        finally {
            setIsSaving(false);
        }
    };
    const tabs = [
        { id: 'business', label: 'Business', icon: '🏢' },
        { id: 'dashboard', label: 'Dashboard', icon: '📊' },
        { id: 'ai', label: 'AI Assistant', icon: '🤖' },
        { id: 'notifications', label: 'Notifications', icon: '🔔' },
    ];
    return (_jsx("div", { className: "fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4", children: _jsxs("div", { className: "bg-white rounded-2xl shadow-2xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col", children: [_jsxs("div", { className: "flex items-center justify-between p-6 border-b bg-gray-50", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-bold text-gray-900", children: "Settings" }), _jsx("p", { className: "text-sm text-gray-500 mt-1", children: "Manage your account and preferences" })] }), _jsx("button", { onClick: onClose, className: "p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-lg transition-colors", "aria-label": "Close settings", children: _jsx("svg", { className: "w-6 h-6", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M6 18L18 6M6 6l12 12" }) }) })] }), _jsx("div", { className: "border-b bg-white", children: _jsx("div", { className: "flex px-6", children: tabs.map((tab) => (_jsxs("button", { onClick: () => setActiveTab(tab.id), className: `px-4 py-3 font-medium text-sm border-b-2 transition-colors ${activeTab === tab.id
                                ? 'border-blue-500 text-blue-600'
                                : 'border-transparent text-gray-500 hover:text-gray-700'}`, children: [_jsx("span", { className: "mr-2", children: tab.icon }), tab.label] }, tab.id))) }) }), _jsx("div", { className: "flex-1 overflow-y-auto", children: _jsxs("div", { className: "p-6", children: [activeTab === 'business' && (_jsx("div", { className: "space-y-6", children: _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-4", children: "Business Information" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Business Name" }), _jsx("input", { type: "text", value: business.profile.businessName, onChange: (e) => updateBusinessSettings({
                                                                profile: { ...business.profile, businessName: e.target.value }
                                                            }), className: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent", placeholder: "Enter business name" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Email" }), _jsx("input", { type: "email", value: business.profile.email, onChange: (e) => updateBusinessSettings({
                                                                profile: { ...business.profile, email: e.target.value }
                                                            }), className: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent", placeholder: "Enter email" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Primary Color" }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("input", { type: "color", value: business.branding.colors.primary, onChange: (e) => updateBusinessSettings({
                                                                        branding: { ...business.branding, colors: { ...business.branding.colors, primary: e.target.value } }
                                                                    }), className: "w-12 h-10 cursor-pointer rounded-lg border border-gray-300" }), _jsx("span", { className: "text-sm text-gray-600", children: business.branding.colors.primary })] })] })] })] }) })), activeTab === 'dashboard' && (_jsx("div", { className: "space-y-6", children: _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-4", children: "Dashboard Preferences" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-center justify-between p-4 bg-gray-50 rounded-lg", children: [_jsxs("div", { children: [_jsx("span", { className: "font-medium text-gray-900", children: "Layout Locked" }), _jsx("p", { className: "text-sm text-gray-500", children: "Prevent accidental widget movement" })] }), _jsxs("label", { className: "relative inline-flex items-center cursor-pointer", children: [_jsx("input", { type: "checkbox", checked: dashboard.layoutLocked, onChange: (e) => updateDashboardSettings({ layoutLocked: e.target.checked }), className: "sr-only peer" }), _jsx("div", { className: "w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600" })] })] }), _jsxs("div", { className: "p-4 bg-gray-50 rounded-lg", children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Auto-refresh Interval" }), _jsx("input", { type: "range", min: "30", max: "1800", step: "30", value: dashboard.refreshInterval, onChange: (e) => updateDashboardSettings({ refreshInterval: parseInt(e.target.value) }), className: "w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer" }), _jsxs("div", { className: "flex justify-between text-sm text-gray-500 mt-2", children: [_jsx("span", { children: "30s" }), _jsxs("span", { className: "font-medium", children: [dashboard.refreshInterval, "s"] }), _jsx("span", { children: "30m" })] })] })] })] }) })), activeTab === 'ai' && (_jsx("div", { className: "space-y-6", children: _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-4", children: "AI Assistant" }), _jsx("div", { className: "space-y-4", children: _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Communication Tone" }), _jsxs("select", { value: ai.personality.tone, onChange: (e) => updateAISettings({
                                                            personality: { ...ai.personality, tone: e.target.value }
                                                        }), className: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent", children: [_jsx("option", { value: "professional", children: "Professional" }), _jsx("option", { value: "friendly", children: "Friendly" }), _jsx("option", { value: "casual", children: "Casual" }), _jsx("option", { value: "formal", children: "Formal" })] })] }) })] }) })), activeTab === 'notifications' && (_jsx("div", { className: "space-y-6", children: _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-4", children: "Notification Preferences" }), _jsxs("div", { className: "space-y-4", children: [Object.entries(notifications.channels).map(([channel, config]) => (_jsxs("div", { className: "flex items-center justify-between p-4 bg-gray-50 rounded-lg", children: [_jsx("div", { children: _jsxs("span", { className: "font-medium text-gray-900 capitalize", children: [channel, " Notifications"] }) }), _jsxs("label", { className: "relative inline-flex items-center cursor-pointer", children: [_jsx("input", { type: "checkbox", checked: config.enabled, onChange: (e) => updateNotificationSettings({
                                                                        channels: {
                                                                            ...notifications.channels,
                                                                            [channel]: { ...config, enabled: e.target.checked }
                                                                        }
                                                                    }), className: "sr-only peer" }), _jsx("div", { className: "w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600" })] })] }, channel))), _jsxs("div", { className: "flex items-center justify-between p-4 bg-gray-50 rounded-lg", children: [_jsxs("div", { children: [_jsx("span", { className: "font-medium text-gray-900", children: "Quiet Hours" }), _jsx("p", { className: "text-sm text-gray-500", children: "Pause notifications during specified hours" })] }), _jsxs("label", { className: "relative inline-flex items-center cursor-pointer", children: [_jsx("input", { type: "checkbox", checked: notifications.quietHours.enabled, onChange: (e) => updateNotificationSettings({
                                                                        quietHours: { ...notifications.quietHours, enabled: e.target.checked }
                                                                    }), className: "sr-only peer" }), _jsx("div", { className: "w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600" })] })] }), notifications.quietHours.enabled && (_jsxs("div", { className: "grid grid-cols-2 gap-4 p-4 bg-blue-50 rounded-lg border border-blue-100", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Start Time" }), _jsx("input", { type: "time", value: notifications.quietHours.startTime, onChange: (e) => updateNotificationSettings({
                                                                        quietHours: { ...notifications.quietHours, startTime: e.target.value }
                                                                    }), className: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "End Time" }), _jsx("input", { type: "time", value: notifications.quietHours.endTime, onChange: (e) => updateNotificationSettings({
                                                                        quietHours: { ...notifications.quietHours, endTime: e.target.value }
                                                                    }), className: "w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" })] })] }))] })] }) }))] }) }), _jsxs("div", { className: "flex justify-end gap-3 p-6 border-t bg-gray-50", children: [_jsx("button", { onClick: onClose, className: "px-4 py-2 text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-500", children: "Cancel" }), _jsx("button", { onClick: handleSave, disabled: isSaving, className: "px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2", children: isSaving ? (_jsxs(_Fragment, { children: [_jsxs("svg", { className: "animate-spin h-4 w-4", viewBox: "0 0 24 24", children: [_jsx("circle", { className: "opacity-25", cx: "12", cy: "12", r: "10", stroke: "currentColor", strokeWidth: "4", fill: "none" }), _jsx("path", { className: "opacity-75", fill: "currentColor", d: "M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" })] }), "Saving..."] })) : ('Save Settings') })] })] }) }));
}
