'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { BookOpen, Users, DollarSign, TrendingUp } from 'lucide-react';
import { UniversalSectionHeader } from './universal';
export function ActiveCoursesSection({ courses, _designCategory }) {
    const publishedCourses = courses.filter(c => c.status === 'published');
    const totalEnrolled = courses.reduce((sum, c) => sum + c.enrolledStudents, 0);
    const totalRevenue = courses.reduce((sum, c) => sum + (c.revenue || 0), 0);
    return (_jsxs("div", { className: "space-y-4", children: [_jsx(UniversalSectionHeader, { title: "Active Courses", subtitle: `${publishedCourses.length} published courses`, icon: _jsx(BookOpen, { className: "h-5 w-5" }) }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-3 gap-4", children: [_jsx(Card, { className: "bg-card border-border/50 rounded-2xl", children: _jsx(CardContent, { className: "p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-muted-foreground mb-1", children: "Total Students" }), _jsx("p", { className: "text-3xl font-bold text-foreground", children: totalEnrolled })] }), _jsx("div", { className: "p-3 rounded-xl bg-primary/10", children: _jsx(Users, { className: "h-6 w-6 text-primary" }) })] }) }) }), _jsx(Card, { className: "bg-card border-border/50 rounded-2xl", children: _jsx(CardContent, { className: "p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-muted-foreground mb-1", children: "Total Revenue" }), _jsxs("p", { className: "text-3xl font-bold text-foreground", children: ["$", totalRevenue.toLocaleString()] })] }), _jsx("div", { className: "p-3 rounded-xl bg-emerald-500/10", children: _jsx(DollarSign, { className: "h-6 w-6 text-emerald-500" }) })] }) }) }), _jsx(Card, { className: "bg-card border-border/50 rounded-2xl", children: _jsx(CardContent, { className: "p-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-muted-foreground mb-1", children: "Avg Progress" }), _jsxs("p", { className: "text-3xl font-bold text-foreground", children: [courses.length > 0
                                                        ? Math.round(courses.reduce((sum, c) => sum + c.progress, 0) / courses.length)
                                                        : 0, "%"] })] }), _jsx("div", { className: "p-3 rounded-xl bg-blue-500/10", children: _jsx(TrendingUp, { className: "h-6 w-6 text-blue-500" }) })] }) }) })] }), _jsx("div", { className: "space-y-3", children: courses.slice(0, 6).map((course) => (_jsx(Card, { className: "bg-card border-border/50 hover:border-primary/50 transition-all rounded-2xl", children: _jsx(CardContent, { className: "p-4", children: _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("h4", { className: "font-semibold text-lg", children: course.title }), _jsx(Badge, { variant: course.status === 'published' ? 'default' : 'secondary', className: "rounded-full px-2 py-0.5 text-xs", children: course.status })] }), _jsxs("p", { className: "text-sm text-muted-foreground", children: ["Instructor: ", course.instructorName || 'Not assigned'] })] }), _jsxs("div", { className: "text-right", children: [_jsxs("p", { className: "text-2xl font-bold text-emerald-500", children: ["$", course.revenue?.toLocaleString() || 0] }), _jsx("p", { className: "text-xs text-muted-foreground", children: "revenue" })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex items-center justify-between text-sm", children: [_jsxs("span", { className: "text-muted-foreground", children: [course.enrolledStudents, "/", course.maxStudents, " students"] }), _jsxs("span", { className: "font-medium text-foreground", children: [course.progress, "% complete"] })] }), _jsx(Progress, { value: course.progress, className: "h-2 rounded-full", style: {
                                                background: 'linear-gradient(90deg, rgba(16,185,129,0.2) 0%, rgba(16,185,129,0.6) 100%)'
                                            } })] }), course.rating && (_jsxs("div", { className: "flex items-center gap-2 text-sm", children: [_jsx(TrendingUp, { className: "h-4 w-4 text-yellow-500" }), _jsx("span", { className: "font-medium text-foreground", children: course.rating.toFixed(1) }), _jsx("span", { className: "text-muted-foreground", children: "rating" })] }))] }) }) }, course.id))) })] }));
}
